import { CryptoboardApp } from "./CryptoboardApp"

export const routes = [{ path: "/cryptoboard/*", element: <CryptoboardApp /> }]

export const nav = [
  {
    path: "/cryptoboard",
    icon: "CandlestickChart",
    labelKey: "cryptoboard",
    group: "working",
    roles: [] as ("admin" | "user")[],
  },
]

export const i18n = {
  de: {
    cryptoboard: {
      title: "Cryptoboard",
      subtitle: "Kurse, Charts & News",
      nav_dashboard: "Übersicht",
      nav_portfolio: "Portfolio",
      nav_analytics: "Auswertung",
      nav_tradelog: "Trades",
      nav_compare: "Vergleich",
      nav_alerts: "Alarme",
      nav_news: "News",
      al_new_title: "Alarm erstellen",
      al_rules: "Aktive Alarme",
      al_history: "Ausgelöste Alarme",
      al_empty: "Noch keine Alarme — oben erstellen.",
      al_history_empty: "Noch nichts ausgelöst.",
      al_create: "Erstellen",
      al_portfolio: "Portfolio",
      al_threshold_eur: "Schwelle (€)",
      al_threshold_pct: "Schwelle (%)",
      al_kind_price_above: "Kurs über",
      al_kind_price_below: "Kurs unter",
      al_kind_pct_change_24h_above: "24h-Änd. über",
      al_kind_pct_change_24h_below: "24h-Änd. unter",
      al_kind_portfolio_above: "Portfolio über",
      al_kind_portfolio_below: "Portfolio unter",
      al_err_coin: "Bitte einen Coin auswählen.",
      al_err_threshold: "Bitte eine gültige Schwelle eingeben.",
      al_err_save: "Speichern fehlgeschlagen.",
      fng_title: "Fear & Greed Index",
      fng_unavailable: "Sentiment nicht verfügbar.",
      ind_title: "Technische Analyse",
      ind_price_ma: "Kurs & gleitende Durchschnitte",
      ind_price: "Kurs",
      ind_rsi: "RSI (14)",
      ind_macd: "MACD (12/26/9)",
      cmp_title: "Performance-Vergleich (% seit Start)",
      cmp_add_coin: "Coin…",
      cmp_tf_7: "7T",
      cmp_tf_30: "30T",
      cmp_tf_90: "90T",
      cmp_tf_365: "1J",
      pf_total_value: "Gesamtwert",
      pf_unrealized: "Nicht realisiert",
      pf_realized: "Realisiert (FIFO)",
      pf_cost_basis: "Einstandskosten",
      pf_positions: "Positionen",
      pf_allocation: "Verteilung",
      pf_holdings: "Bestände",
      pf_empty: "Noch keine Bestände — trage einen Trade ein.",
      pf_closed: "geschlossen",
      pf_col_coin: "Coin",
      pf_col_qty: "Menge",
      pf_col_avg: "Ø-Einstand",
      pf_col_price: "Kurs",
      pf_col_value: "Wert",
      pf_col_pnl: "G/V",
      pf_col_alloc: "Anteil",
      tx_add_title: "Trade hinzufügen",
      tx_edit_title: "Trade bearbeiten",
      tx_empty: "Noch keine Transaktionen erfasst.",
      tx_kind_buy: "Kauf",
      tx_kind_sell: "Verkauf",
      tx_kind_transfer_in: "Eingang",
      tx_kind_transfer_out: "Ausgang",
      tx_quantity: "Menge",
      tx_price: "Stückpreis (€)",
      tx_fee: "Gebühr (€)",
      tx_date: "Datum",
      tx_note: "Notiz",
      tx_optional: "optional",
      tx_add: "Hinzufügen",
      tx_save: "Speichern",
      tx_cancel: "Abbrechen",
      tx_confirm_delete: "Diese Transaktion wirklich löschen?",
      tx_clear_all: "Alle löschen",
      tx_confirm_clear: "Wirklich ALLE {n} Transaktionen löschen? Das kann nicht rückgängig gemacht werden.",
      tx_col_date: "Datum",
      tx_col_kind: "Art",
      tx_col_coin: "Coin",
      tx_col_qty: "Menge",
      tx_col_price: "Preis",
      tx_col_fee: "Gebühr",
      tx_err_coin: "Bitte einen Coin auswählen.",
      tx_err_qty: "Menge muss größer als 0 sein.",
      tx_err_save: "Speichern fehlgeschlagen.",
      imp_title: "CSV importieren",
      imp_choose_file: "CSV-Datei wählen (Wallet-Export)",
      imp_field_kind: "Art",
      imp_field_symbol: "Coin",
      imp_field_quantity: "Menge",
      imp_field_price: "Preis",
      imp_field_fee: "Gebühr",
      imp_field_executed_at: "Datum",
      imp_col_coin: "Coin",
      imp_col_status: "Status",
      imp_ready: "importierbar",
      imp_duplicate: "bereits importiert",
      imp_unresolved: "Coin nicht erkannt",
      imp_ok: "bereit",
      imp_skipped_rows: "fehlerhafte Zeilen",
      imp_commit: "Importieren",
      imp_nothing: "Nichts zu importieren.",
      imp_err_parse: "CSV konnte nicht gelesen werden.",
      imp_err_commit: "Import fehlgeschlagen.",
      an_loading: "Kursdaten werden geladen … (beim ersten Mal etwas Geduld)",
      an_value_history: "Portfolio-Wert (letzte 12 Monate)",
      an_current: "Aktueller Wert",
      an_ath: "Allzeithoch",
      an_change_30d: "30 Tage",
      an_change_1y: "1 Jahr",
      an_empty: "Noch keine Daten — importiere zuerst Transaktionen.",
      an_missing: "Keine Kurshistorie für",
      an_disclaimer: "Reiner Marktwert der letzten 12 Monate (EUR, Tageskurse). Längere Historie nur mit kostenpflichtigem Kurs-Abo. Kein Gewinn/Verlust, keine Steuerangabe.",
      search_placeholder: "Coin suchen (z.B. Bitcoin)…",
      search_empty: "Keine Treffer",
      watchlist: "Watchlist",
      watchlist_empty: "Noch keine Coins — oben suchen und hinzufügen.",
      top_coins: "Top nach Marktkapitalisierung",
      add_watch: "Zur Watchlist",
      remove_watch: "Aus Watchlist entfernen",
      col_price: "Preis",
      col_24h: "24h",
      col_7d: "7d",
      col_cap: "Marktkap.",
      col_vol: "Volumen (24h)",
      rank: "Rang",
      ath: "Allzeithoch",
      atl: "Allzeittief",
      circulating: "Umlauf",
      total_supply: "Gesamt",
      max_supply: "Max",
      news_title: "Krypto-News",
      news_empty: "Keine News verfügbar.",
      news_source: "Quelle",
      back: "Zurück",
      loading: "Laden…",
      error: "Konnte nicht laden.",
      tf_24h: "24h",
      tf_7d: "7T",
      tf_30d: "30T",
      tf_1y: "1J",
    },
  },
  en: {
    cryptoboard: {
      title: "Cryptoboard",
      subtitle: "Prices, charts & news",
      nav_dashboard: "Overview",
      nav_portfolio: "Portfolio",
      nav_analytics: "Analytics",
      nav_tradelog: "Trades",
      nav_compare: "Compare",
      nav_alerts: "Alerts",
      nav_news: "News",
      al_new_title: "Create alert",
      al_rules: "Active alerts",
      al_history: "Triggered alerts",
      al_empty: "No alerts yet — create one above.",
      al_history_empty: "Nothing triggered yet.",
      al_create: "Create",
      al_portfolio: "Portfolio",
      al_threshold_eur: "Threshold (€)",
      al_threshold_pct: "Threshold (%)",
      al_kind_price_above: "Price above",
      al_kind_price_below: "Price below",
      al_kind_pct_change_24h_above: "24h change above",
      al_kind_pct_change_24h_below: "24h change below",
      al_kind_portfolio_above: "Portfolio above",
      al_kind_portfolio_below: "Portfolio below",
      al_err_coin: "Please select a coin.",
      al_err_threshold: "Please enter a valid threshold.",
      al_err_save: "Save failed.",
      fng_title: "Fear & Greed Index",
      fng_unavailable: "Sentiment unavailable.",
      ind_title: "Technical analysis",
      ind_price_ma: "Price & moving averages",
      ind_price: "Price",
      ind_rsi: "RSI (14)",
      ind_macd: "MACD (12/26/9)",
      cmp_title: "Performance comparison (% since start)",
      cmp_add_coin: "Coin…",
      cmp_tf_7: "7d",
      cmp_tf_30: "30d",
      cmp_tf_90: "90d",
      cmp_tf_365: "1y",
      pf_total_value: "Total value",
      pf_unrealized: "Unrealized",
      pf_realized: "Realized (FIFO)",
      pf_cost_basis: "Cost basis",
      pf_positions: "positions",
      pf_allocation: "Allocation",
      pf_holdings: "Holdings",
      pf_empty: "No holdings yet — add a trade.",
      pf_closed: "closed",
      pf_col_coin: "Coin",
      pf_col_qty: "Quantity",
      pf_col_avg: "Avg cost",
      pf_col_price: "Price",
      pf_col_value: "Value",
      pf_col_pnl: "P&L",
      pf_col_alloc: "Alloc.",
      tx_add_title: "Add trade",
      tx_edit_title: "Edit trade",
      tx_empty: "No transactions recorded yet.",
      tx_kind_buy: "Buy",
      tx_kind_sell: "Sell",
      tx_kind_transfer_in: "Transfer in",
      tx_kind_transfer_out: "Transfer out",
      tx_quantity: "Quantity",
      tx_price: "Unit price (€)",
      tx_fee: "Fee (€)",
      tx_date: "Date",
      tx_note: "Note",
      tx_optional: "optional",
      tx_add: "Add",
      tx_save: "Save",
      tx_cancel: "Cancel",
      tx_confirm_delete: "Really delete this transaction?",
      tx_clear_all: "Delete all",
      tx_confirm_clear: "Really delete ALL {n} transactions? This cannot be undone.",
      tx_col_date: "Date",
      tx_col_kind: "Type",
      tx_col_coin: "Coin",
      tx_col_qty: "Quantity",
      tx_col_price: "Price",
      tx_col_fee: "Fee",
      tx_err_coin: "Please select a coin.",
      tx_err_qty: "Quantity must be greater than 0.",
      tx_err_save: "Save failed.",
      imp_title: "Import CSV",
      imp_choose_file: "Choose CSV file (wallet export)",
      imp_field_kind: "Type",
      imp_field_symbol: "Coin",
      imp_field_quantity: "Quantity",
      imp_field_price: "Price",
      imp_field_fee: "Fee",
      imp_field_executed_at: "Date",
      imp_col_coin: "Coin",
      imp_col_status: "Status",
      imp_ready: "importable",
      imp_duplicate: "already imported",
      imp_unresolved: "coin not recognized",
      imp_ok: "ready",
      imp_skipped_rows: "invalid rows",
      imp_commit: "Import",
      imp_nothing: "Nothing to import.",
      imp_err_parse: "Could not read CSV.",
      imp_err_commit: "Import failed.",
      an_loading: "Loading price data … (first time may take a moment)",
      an_value_history: "Portfolio value (last 12 months)",
      an_current: "Current value",
      an_ath: "All-time high",
      an_change_30d: "30 days",
      an_change_1y: "1 year",
      an_empty: "No data yet — import transactions first.",
      an_missing: "No price history for",
      an_disclaimer: "Market value of the last 12 months (EUR, daily prices). Longer history requires a paid price plan. No profit/loss, no tax statement.",
      search_placeholder: "Search a coin (e.g. Bitcoin)…",
      search_empty: "No matches",
      watchlist: "Watchlist",
      watchlist_empty: "No coins yet — search above and add.",
      top_coins: "Top by market cap",
      add_watch: "Add to watchlist",
      remove_watch: "Remove from watchlist",
      col_price: "Price",
      col_24h: "24h",
      col_7d: "7d",
      col_cap: "Market cap",
      col_vol: "Volume (24h)",
      rank: "Rank",
      ath: "All-time high",
      atl: "All-time low",
      circulating: "Circulating",
      total_supply: "Total",
      max_supply: "Max",
      news_title: "Crypto news",
      news_empty: "No news available.",
      news_source: "Source",
      back: "Back",
      loading: "Loading…",
      error: "Failed to load.",
      tf_24h: "24h",
      tf_7d: "7d",
      tf_30d: "30d",
      tf_1y: "1y",
    },
  },
}
