import { CryptoboardApp } from "./CryptoboardApp"

export const routes = [{ path: "/cryptoboard/*", element: <CryptoboardApp /> }]

export const nav = [
  {
    path: "/cryptoboard",
    icon: "CandlestickChart",
    labelKey: "cryptoboard",
    group: "working",
    roles: [] as ("admin" | "user")[],
  },
]

export const i18n = {
  de: {
    cryptoboard: {
      title: "Cryptoboard",
      subtitle: "Kurse, Charts & News",
      nav_dashboard: "Übersicht",
      nav_portfolio: "Portfolio",
      nav_tradelog: "Trades",
      nav_news: "News",
      pf_total_value: "Gesamtwert",
      pf_unrealized: "Nicht realisiert",
      pf_realized: "Realisiert (FIFO)",
      pf_cost_basis: "Einstandskosten",
      pf_positions: "Positionen",
      pf_allocation: "Verteilung",
      pf_holdings: "Bestände",
      pf_empty: "Noch keine Bestände — trage einen Trade ein.",
      pf_closed: "geschlossen",
      pf_col_coin: "Coin",
      pf_col_qty: "Menge",
      pf_col_avg: "Ø-Einstand",
      pf_col_price: "Kurs",
      pf_col_value: "Wert",
      pf_col_pnl: "G/V",
      pf_col_alloc: "Anteil",
      tx_add_title: "Trade hinzufügen",
      tx_edit_title: "Trade bearbeiten",
      tx_empty: "Noch keine Transaktionen erfasst.",
      tx_kind_buy: "Kauf",
      tx_kind_sell: "Verkauf",
      tx_kind_transfer_in: "Eingang",
      tx_kind_transfer_out: "Ausgang",
      tx_quantity: "Menge",
      tx_price: "Stückpreis (€)",
      tx_fee: "Gebühr (€)",
      tx_date: "Datum",
      tx_note: "Notiz",
      tx_optional: "optional",
      tx_add: "Hinzufügen",
      tx_save: "Speichern",
      tx_cancel: "Abbrechen",
      tx_confirm_delete: "Diese Transaktion wirklich löschen?",
      tx_col_date: "Datum",
      tx_col_kind: "Art",
      tx_col_coin: "Coin",
      tx_col_qty: "Menge",
      tx_col_price: "Preis",
      tx_col_fee: "Gebühr",
      tx_err_coin: "Bitte einen Coin auswählen.",
      tx_err_qty: "Menge muss größer als 0 sein.",
      tx_err_save: "Speichern fehlgeschlagen.",
      search_placeholder: "Coin suchen (z.B. Bitcoin)…",
      search_empty: "Keine Treffer",
      watchlist: "Watchlist",
      watchlist_empty: "Noch keine Coins — oben suchen und hinzufügen.",
      top_coins: "Top nach Marktkapitalisierung",
      add_watch: "Zur Watchlist",
      remove_watch: "Aus Watchlist entfernen",
      col_price: "Preis",
      col_24h: "24h",
      col_7d: "7d",
      col_cap: "Marktkap.",
      col_vol: "Volumen (24h)",
      rank: "Rang",
      ath: "Allzeithoch",
      atl: "Allzeittief",
      circulating: "Umlauf",
      total_supply: "Gesamt",
      max_supply: "Max",
      news_title: "Krypto-News",
      news_empty: "Keine News verfügbar.",
      news_source: "Quelle",
      back: "Zurück",
      loading: "Laden…",
      error: "Konnte nicht laden.",
      tf_24h: "24h",
      tf_7d: "7T",
      tf_30d: "30T",
      tf_1y: "1J",
    },
  },
  en: {
    cryptoboard: {
      title: "Cryptoboard",
      subtitle: "Prices, charts & news",
      nav_dashboard: "Overview",
      nav_portfolio: "Portfolio",
      nav_tradelog: "Trades",
      nav_news: "News",
      pf_total_value: "Total value",
      pf_unrealized: "Unrealized",
      pf_realized: "Realized (FIFO)",
      pf_cost_basis: "Cost basis",
      pf_positions: "positions",
      pf_allocation: "Allocation",
      pf_holdings: "Holdings",
      pf_empty: "No holdings yet — add a trade.",
      pf_closed: "closed",
      pf_col_coin: "Coin",
      pf_col_qty: "Quantity",
      pf_col_avg: "Avg cost",
      pf_col_price: "Price",
      pf_col_value: "Value",
      pf_col_pnl: "P&L",
      pf_col_alloc: "Alloc.",
      tx_add_title: "Add trade",
      tx_edit_title: "Edit trade",
      tx_empty: "No transactions recorded yet.",
      tx_kind_buy: "Buy",
      tx_kind_sell: "Sell",
      tx_kind_transfer_in: "Transfer in",
      tx_kind_transfer_out: "Transfer out",
      tx_quantity: "Quantity",
      tx_price: "Unit price (€)",
      tx_fee: "Fee (€)",
      tx_date: "Date",
      tx_note: "Note",
      tx_optional: "optional",
      tx_add: "Add",
      tx_save: "Save",
      tx_cancel: "Cancel",
      tx_confirm_delete: "Really delete this transaction?",
      tx_col_date: "Date",
      tx_col_kind: "Type",
      tx_col_coin: "Coin",
      tx_col_qty: "Quantity",
      tx_col_price: "Price",
      tx_col_fee: "Fee",
      tx_err_coin: "Please select a coin.",
      tx_err_qty: "Quantity must be greater than 0.",
      tx_err_save: "Save failed.",
      search_placeholder: "Search a coin (e.g. Bitcoin)…",
      search_empty: "No matches",
      watchlist: "Watchlist",
      watchlist_empty: "No coins yet — search above and add.",
      top_coins: "Top by market cap",
      add_watch: "Add to watchlist",
      remove_watch: "Remove from watchlist",
      col_price: "Price",
      col_24h: "24h",
      col_7d: "7d",
      col_cap: "Market cap",
      col_vol: "Volume (24h)",
      rank: "Rank",
      ath: "All-time high",
      atl: "All-time low",
      circulating: "Circulating",
      total_supply: "Total",
      max_supply: "Max",
      news_title: "Crypto news",
      news_empty: "No news available.",
      news_source: "Source",
      back: "Back",
      loading: "Loading…",
      error: "Failed to load.",
      tf_24h: "24h",
      tf_7d: "7d",
      tf_30d: "30d",
      tf_1y: "1y",
    },
  },
}
