import { CryptoboardApp } from "./CryptoboardApp"

export const routes = [{ path: "/cryptoboard/*", element: <CryptoboardApp /> }]

export const nav = [
  {
    path: "/cryptoboard",
    icon: "CandlestickChart",
    labelKey: "cryptoboard",
    group: "working",
    roles: [] as ("admin" | "user")[],
  },
]

export const i18n = {
  de: {
    cryptoboard: {
      title: "Cryptoboard",
      subtitle: "Kurse, Charts & News",
      nav_dashboard: "Übersicht",
      nav_news: "News",
      search_placeholder: "Coin suchen (z.B. Bitcoin)…",
      search_empty: "Keine Treffer",
      watchlist: "Watchlist",
      watchlist_empty: "Noch keine Coins — oben suchen und hinzufügen.",
      top_coins: "Top nach Marktkapitalisierung",
      add_watch: "Zur Watchlist",
      remove_watch: "Aus Watchlist entfernen",
      col_price: "Preis",
      col_24h: "24h",
      col_7d: "7d",
      col_cap: "Marktkap.",
      col_vol: "Volumen (24h)",
      rank: "Rang",
      ath: "Allzeithoch",
      atl: "Allzeittief",
      circulating: "Umlauf",
      total_supply: "Gesamt",
      max_supply: "Max",
      news_title: "Krypto-News",
      news_empty: "Keine News verfügbar.",
      news_source: "Quelle",
      back: "Zurück",
      loading: "Laden…",
      error: "Konnte nicht laden.",
      tf_24h: "24h",
      tf_7d: "7T",
      tf_30d: "30T",
      tf_1y: "1J",
    },
  },
  en: {
    cryptoboard: {
      title: "Cryptoboard",
      subtitle: "Prices, charts & news",
      nav_dashboard: "Overview",
      nav_news: "News",
      search_placeholder: "Search a coin (e.g. Bitcoin)…",
      search_empty: "No matches",
      watchlist: "Watchlist",
      watchlist_empty: "No coins yet — search above and add.",
      top_coins: "Top by market cap",
      add_watch: "Add to watchlist",
      remove_watch: "Remove from watchlist",
      col_price: "Price",
      col_24h: "24h",
      col_7d: "7d",
      col_cap: "Market cap",
      col_vol: "Volume (24h)",
      rank: "Rank",
      ath: "All-time high",
      atl: "All-time low",
      circulating: "Circulating",
      total_supply: "Total",
      max_supply: "Max",
      news_title: "Crypto news",
      news_empty: "No news available.",
      news_source: "Source",
      back: "Back",
      loading: "Loading…",
      error: "Failed to load.",
      tf_24h: "24h",
      tf_7d: "7d",
      tf_30d: "30d",
      tf_1y: "1y",
    },
  },
}
