// Oberflächentexte Englisch – gleiche Schlüssel wie texts.de.ts (Typ erzwingt Vollständigkeit).
import type { Texts } from "./texts.de"

export const textsEn: Texts = {
  title: "Storyteller",
  subtitle: "Write books and stories – the AI only suggests, you decide.",
  draft_badge: "Draft",
  draft_hint: "Clickable draft: books are stored in this browser only, AI suggestions are placeholders.",
  project: "Project",
  project_pick: "Choose project …",
  project_none: "You are not in any project. Books always belong to a project.",
  books: "Books",
  books_empty: "No book in this project yet.",
  new_book: "New book",
  sample_book: "Load sample book (“Die Verwandlung”)",
  continue_last: "Continue writing",
  open: "Open",
  delete_book: "Delete",
  delete_confirm: "Really delete “{{title}}”? This cannot be undone in the draft.",
  words_n: "{{n}} words",
  edited_at: "edited {{when}}",
  nb_title: "Title",
  nb_kind: "Type",
  kind_novel: "Novel",
  kind_story: "Story",
  kind_nonfiction: "Non-fiction",
  kind_learning: "Textbook",
  nb_language: "Language",
  nb_audience: "Audience",
  nb_audience_ph: "e.g. teens 14+",
  nb_idea: "Idea (optional)",
  nb_idea_ph: "What is it about? 1–3 sentences.",
  nb_create: "Create book",
  cancel: "Cancel",
  back_books: "Books",
  view_write: "Write",
  view_plan: "Plan",
  view_ask: "Ask",
  soon: "coming soon",
  focus: "Focus mode (Ctrl+Shift+F)",
  toggle_left: "Toggle navigator (Ctrl+B)",
  toggle_right: "Toggle context (Ctrl+J)",
  structure: "Outline",
  add_scene: "Add scene",
  add_chapter: "Add chapter",
  rename: "Rename",
  remove_scene: "Delete scene",
  remove_scene_confirm: "Delete scene “{{title}}”?",
  move_up: "Move up (Alt+↑)",
  move_down: "Move down (Alt+↓)",
  drag_hint: "Scenes can be dragged with the mouse.",
  read_chapter: "Read whole chapter",
  back_to_scene: "Back to scene",
  placeholder: "Start writing …",
  tab_scene: "Scene",
  tab_entity: "Profile",
  tab_ai: "AI",
  tab_notes: "Notes",
  scene_title: "Title",
  scene_summary: "Summary",
  scene_summary_ph: "What happens in this scene? 1–3 sentences.",
  scene_pov: "Point of view",
  scene_pov_none: "– none –",
  scene_status: "Status",
  status_idea: "Idea",
  status_draft: "Draft",
  status_revised: "Revised",
  status_done: "Done",
  in_scene: "In this scene",
  in_scene_none: "No profiles detected.",
  snapshots: "Snapshots",
  snapshot_now: "Snapshot now",
  snapshot_restore: "Restore",
  snapshot_restore_confirm: "Reset the scene to {{when}}? The current state is saved as a snapshot first.",
  snapshots_none: "None yet. One is created automatically before every accepted AI suggestion.",
  group_character: "Characters",
  group_place: "Places",
  group_item: "Items",
  group_term: "Terms",
  group_person: "People",
  group_source: "Sources",
  add_entity: "New",
  entity_none: "Pick a profile on the left or create one.",
  entity_name: "Name",
  entity_aliases: "Nicknames / other names",
  entity_aliases_ph: "comma separated",
  entity_desc: "Description",
  entity_fields: "Properties",
  entity_field_key: "e.g. eye colour",
  entity_field_value: "e.g. green",
  entity_field_add: "Add property",
  entity_delete: "Delete profile",
  entity_delete_confirm: "Delete profile “{{name}}”?",
  entity_new_name: "New entry",
  ai_intro: "Select text in the editor and pick an action. Without a selection the AI continues at the cursor.",
  ai_rewrite: "Rewrite",
  ai_expand: "Expand",
  ai_shorten: "Shorten",
  ai_continue: "Continue",
  ai_placeholder_note: "Draft: the AI is still a placeholder and produces sample text.",
  ai_proposal: "Suggestion",
  ai_accept: "Accept (Ctrl+Enter)",
  ai_reject: "Reject (Esc)",
  ai_again: "Again",
  ai_stale: "The scene has changed in the meantime. Please request again.",
  ai_history: "History for this scene",
  ai_history_none: "No suggestions yet.",
  ai_state_accepted: "accepted",
  ai_state_rejected: "rejected",
  ai_model: "Model: default (not active in the draft)",
  notes_ph: "Free notes for the book: ideas, open questions, research …",
  saved: "Saved",
  saving: "Saving …",
  save_failed: "Saving failed – text stays in this window, please do not close it",
  w_scene: "Scene",
  w_chapter: "Chapter",
  w_book: "Book",
  words_unit: "words",
  shortcuts: "Shortcuts",
  shortcuts_list: "Ctrl+B navigator · Ctrl+J context · Ctrl+Shift+F focus · Alt+↑/↓ move scene · Ctrl+Z undo",
}
