// UI texts English for the team buttons (T1e; part of texts.en.ts). Same keys as texts.team.de.ts.
import type { teamDe } from "./texts.team.de"

export const teamEn: typeof teamDe = {
  job_heading: "Ask the team",
  job_hint: "One click sends exactly one helper – no chat. The result shows up below as a finding or proposal.",
  job_check_scene: "Check scene",
  job_edit_scene: "Line edit",
  job_critique_chapter: "Critical read",
  job_structure_chapter: "Check structure",
  job_update_profiles: "Update profiles",
  job_scope_scene: "for this scene",
  job_scope_chapter: "for this chapter",
  job_unavailable: "This helper does not exist in this project.",
  job_confirm: "{{label}} – “{{place}}”",
  job_estimate: "approx. {{cents}} cents ({{model}})",
  job_estimate_unknown: "cost unknown ({{model}})",
  job_start: "Start",
  job_cancel_confirm: "Cancel",
  job_running: "running …",
  job_queued: "waiting …",
  job_done: "done",
  job_error: "error",
  job_cancelled: "cancelled",
  job_stop: "Stop",
  job_cost: "{{cents}} cents",
  job_recent: "Recent jobs",
  job_open_session: "Log",
  ai_err_job_busy: "This helper is already working on this book – please wait until it is done.",
  ai_err_too_many_jobs: "3 jobs are already running for this book – please wait.",
  ai_err_helper_missing: "This helper does not exist in this project.",
  ai_err_place_not_found: "The scene or chapter no longer exists.",
  ai_err_job_not_active: "The job is no longer running.",
}
