// UI texts English for "nothing gets lost" (A2 proposal history, A3 trash; part of texts.en.ts). Same keys as texts.keep.de.ts.
import type { keepDe } from "./texts.keep.de"

export const keepEn: typeof keepDe = {
  history_title: "Earlier proposals",
  history_none: "None. Replaced and discarded proposals end up here and can be brought back.",
  history_kind_text: "Text",
  history_kind_info: "Info",
  history_from: "by {{who}}",
  history_from_agent: "agent",
  history_from_run: "ghostwriter run",
  history_words: "{{n}} words",
  history_discarded: "discarded",
  history_replaced_by: "replaced by {{who}}",
  history_restore: "Bring back",
  history_restored_over: "set aside (an older one was brought back)",
  proposal_from_named: "Proposal by {{who}} ({{words}} words). Your text stays until you accept.",
  replaced_hint: "Replaces a proposal by {{who}} – it is kept under “Earlier proposals” (tab “Scene”).",
  trash_title: "Trash",
  trash_scenes_none: "No deleted scenes.",
  trash_books_none: "No deleted books.",
  trash_deleted_at: "deleted {{when}}",
  trash_restore: "Restore",
  trash_back_original: "goes back to its old place in “{{chapter}}”",
  trash_back_end: "goes to the end of the first chapter (its old chapter is gone)",
  trash_restored_original: "“{{title}}” is back at its old place.",
  trash_restored_end: "“{{title}}” is back – at the end of the first chapter.",
  trash_book_restored: "“{{title}}” is back in the list.",
  trash_scenes_n: "{{n}} scene(s), {{words}} words",
  trash_moved: "moved to a project of its own – backup (the book lives on in the new project)",
  ai_err_scene_exists: "This scene is already back in the book.",
  ai_err_book_exists: "This book is already back in the list.",
  ai_err_trash_entry_not_found: "The entry is no longer in the trash.",
  ai_err_trash_entry_broken: "The entry in the trash is incomplete.",
  // A5c chapter summary
  chapter_summary_title: "Chapter “{{title}}”",
  chapter_summary_ph: "What happens in this chapter? (3–5 sentences – replaces the single scenes of older chapters in the ghostwriter's memory)",
  chapter_summary_hint: "Saved when you leave the field. Without a chapter summary the ghostwriter remembers every scene on its own.",
  chapter_summary_saving: "Saving …",
  chapter_summary_generate: "Generate summary",
  chapter_summary_generate_hint: "The AI condenses the summaries of this chapter's scenes. Nothing is saved until you accept.",
  chapter_summary_proposal: "AI proposal – not saved yet",
  chapter_summary_accept: "Accept",
  chapter_summary_discard: "Discard",
  chapter_summary_conflict: "The chapter summary was changed elsewhere in the meantime. Your text is still in the field – it will be saved when you leave it again.",
  chapter_summary_err_summaries_required: "The scenes of this chapter have no summaries yet – the chapter summary is built from them.",
  chapter_summary_err_ai_busy: "An AI request for this book is already running – please wait.",
  chapter_summary_err_rate_limited: "Too many AI requests – please wait a minute.",
  chapter_summary_err_llm_empty: "The model returned no text.",
  // C1 deleting
  delete_chapter: "Delete chapter",
  delete_scene: "Delete scene",
  delete_section: "Delete section",
  delete_last_scene: "The last scene of the book stays.",
  delete_last_section: "The last section of the book stays.",
  delete_chapter_confirm_scene_one: "Delete chapter “{{title}}” with {{count}} scene? It goes to the trash (bottom of the navigator) with text, snapshots, interview and chapter summary and can be restored there.",
  delete_chapter_confirm_scene_other: "Delete chapter “{{title}}” with {{count}} scenes? It goes to the trash (bottom of the navigator) with text, snapshots, interview and chapter summary and can be restored there.",
  delete_chapter_confirm_section_one: "Delete chapter “{{title}}” with {{count}} section? It goes to the trash (bottom of the navigator) with text, snapshots, interview and chapter summary and can be restored there.",
  delete_chapter_confirm_section_other: "Delete chapter “{{title}}” with {{count}} sections? It goes to the trash (bottom of the navigator) with text, snapshots, interview and chapter summary and can be restored there.",
  delete_scene_confirm_scene: "Delete scene “{{title}}”? It goes to the trash (bottom of the navigator) and can be restored there.",
  delete_scene_confirm_section: "Delete section “{{title}}”? It goes to the trash (bottom of the navigator) and can be restored there.",
  delete_scene_with_chapter_scene: "“{{title}}” is the last scene of chapter “{{chapter}}”. Delete the chapter as well? Both go to the trash.",
  delete_scene_with_chapter_section: "“{{title}}” is the last section of chapter “{{chapter}}”. Delete the chapter as well? Both go to the trash.",
  delete_err_last_chapter: "The last chapter of a book stays.",
  delete_err_run_active: "The ghostwriter is writing in this book right now – please wait or cancel the run.",
  delete_err_job_active: "A team job is working on this book right now – please wait or cancel it.",
  delete_err_chapter_not_found: "The chapter no longer exists.",
  delete_err_scene_not_found: "The scene no longer exists.",
  trash_chapter_label: "Chapter “{{title}}”",
  trash_chapter_n_scene_one: "{{count}} scene",
  trash_chapter_n_scene_other: "{{count}} scenes",
  trash_chapter_n_section_one: "{{count}} section",
  trash_chapter_n_section_other: "{{count}} sections",
  trash_chapter_restored_original: "Chapter “{{title}}” is back at its old place.",
  trash_chapter_restored_end: "Chapter “{{title}}” is back – at the end (its old place is gone).",
  ai_err_chapter_exists: "The chapter or one of its scenes is already back in the book.",
}
