// Oberflächentexte Deutsch für KI-Modi und Ghostwriter (Teil von texts.de.ts, ausgelagert wegen Länge).
// Englisch: texts.ghost.en.ts, gleiche Schlüssel (Typ erzwingt Vollständigkeit).

export const ghostDe = {
  ai_mode: "KI-Modus",
  ai_mode_edit: "Bearbeiten",
  ai_mode_edit_hint: "Markierten Text umschreiben, ausbauen, kürzen oder weiterschreiben",
  ai_mode_scene: "Szene schreiben",
  ai_mode_scene_hint: "Die KI schreibt die ganze Szene aus ihrer Zusammenfassung",
  ai_mode_chapter: "Kapitel/Buch",
  ai_mode_chapter_hint: "",
  ai_mode_interview: "Interview",
  ai_mode_interview_hint: "",
  ai_mode_chat: "Im Chat",
  ai_mode_chat_hint: "",
  ai_model_inherited: "wie Buch ({{model}}})",
  ghost_intro: "Die KI schreibt diese Szene aus ihrer Zusammenfassung, den Steckbriefen und dem, was vorher geschah. Du siehst den Text entstehen und entscheidest danach.",
  ghost_model_label: "Ghostwriter-Modell:",
  ghost_model_default: "Standard",
  ghost_length: "Länge",
  ghost_len_800: "kurz (~800 Wörter)",
  ghost_len_1500: "mittel (~1.500)",
  ghost_len_2500: "lang (~2.500)",
  ghost_len_free: "Wörter",
  ghost_style: "Stil (für dieses Buch)",
  ghost_style_ph: "z. B. Präteritum, nüchtern, lange Sätze, wenig Dialog",
  ghost_reject: "Verwerfen",
  ghost_go_summary: "Zur Zusammenfassung",
  ghost_need_summary: "Erst eine Zusammenfassung für die Szene eintragen (Reiter „Szene“) – daraus schreibt die KI.",
  ghost_has_text: "Die Szene hat schon Text. Das Ergebnis wird als Vorschlag gezeigt; dein Text wird vorher als Schnappschuss gesichert.",
  ghost_estimate: "Schätzung: {{sections}} Abschnitt(e), ~{{out}} Ausgabe- und ~{{in}} Eingabe-Tokens · Modell: {{model}}",
  ghost_start: "Szene schreiben",
  ghost_stop: "Abbrechen",
  ghost_writing: "Schreibt … {{n}} Wörter",
  ghost_ready: "Fertig · {{n}} Wörter",
  ghost_accept: "Übernehmen",
  ghost_accept_replace: "Ersetzen (Schnappschuss davor)",
  ghost_accepted: "Übernommen. Die Szene ist als KI-Entwurf markiert, bis du sie bearbeitest.",
  ai_err_aborted: "Abgebrochen.",
  ai_err_stream_incomplete: "Die Verbindung brach ab, bevor der Text fertig war.",
  ai_err_summary_required: "Erst eine Zusammenfassung für die Szene eintragen.",
  ai_err_length_required: "Bitte eine Länge wählen.",
  ai_err_snapshot_failed: "Schnappschuss ging nicht – Text nicht übernommen.",
  ai_err_network: "Keine Verbindung zum Server.",
  origin_ai_draft: "KI-Entwurf",
  origin_ai_edited: "KI-Entwurf, bearbeitet",
  ai_share: "KI-Anteil {{n}} %",
}

export type GhostTexts = typeof ghostDe
