// Oberflächentexte Deutsch für KI-Modi und Ghostwriter (Teil von texts.de.ts, ausgelagert wegen Länge).
// Englisch: texts.ghost.en.ts, gleiche Schlüssel (Typ erzwingt Vollständigkeit).

export const ghostDe = {
  ai_mode: "KI-Modus",
  ai_mode_edit: "Bearbeiten",
  ai_mode_edit_hint: "Markierten Text umschreiben, ausbauen, kürzen oder weiterschreiben",
  ai_mode_scene: "Szene schreiben",
  ai_mode_scene_hint: "Die KI schreibt die ganze Szene aus ihrer Zusammenfassung",
  ai_mode_chapter: "Kapitel/Buch",
  ai_mode_chapter_hint: "Ein Kapitel, ab hier oder das ganze Buch im Hintergrund schreiben lassen",
  ai_mode_interview: "Interview",
  ai_mode_interview_hint: "Die KI fragt, du erzählst (tippen oder diktieren) – daraus entsteht das Kapitel in deiner Stimme",
  ai_mode_chat: "Im Chat",
  ai_mode_chat_hint: "Mit dem Projekt-Agenten im Chat am Buch arbeiten – er legt Text als Vorschlag ab",
  ai_model_inherited: "wie Buch ({{model}}})",
  ghost_intro: "Die KI schreibt diese Szene aus ihrer Zusammenfassung, den Steckbriefen und dem, was vorher geschah. Du siehst den Text entstehen und entscheidest danach.",
  ghost_model_label: "Ghostwriter-Modell:",
  ghost_model_default: "Standard",
  ghost_length: "Länge",
  ghost_len_800: "kurz (~800 Wörter)",
  ghost_len_1500: "mittel (~1.500)",
  ghost_len_2500: "lang (~2.500)",
  ghost_len_free: "Wörter",
  ghost_style: "Stil (für dieses Buch)",
  ghost_style_ph: "z. B. Präteritum, nüchtern, lange Sätze, wenig Dialog",
  ghost_reject: "Verwerfen",
  ghost_go_summary: "Zur Zusammenfassung",
  ghost_need_summary: "Erst eine Zusammenfassung für die Szene eintragen (Reiter „Szene“) – daraus schreibt die KI.",
  ghost_has_text: "Die Szene hat schon Text. Das Ergebnis wird als Vorschlag gezeigt; dein Text wird vorher als Schnappschuss gesichert.",
  ghost_estimate: "Schätzung: {{sections}} Abschnitt(e), ~{{out}} Ausgabe- und ~{{in}} Eingabe-Tokens · Modell: {{model}}",
  ghost_start: "Szene schreiben",
  ghost_stop: "Abbrechen",
  ghost_writing: "Schreibt … {{n}} Wörter",
  ghost_ready: "Fertig · {{n}} Wörter",
  ghost_accept: "Übernehmen",
  ghost_accept_replace: "Ersetzen (Schnappschuss davor)",
  ghost_accepted: "Übernommen. Die Szene ist als KI-Entwurf markiert, bis du sie bearbeitest.",
  ai_err_aborted: "Abgebrochen.",
  ai_err_stream_incomplete: "Die Verbindung brach ab, bevor der Text fertig war.",
  ai_err_summary_required: "Erst eine Zusammenfassung für die Szene eintragen.",
  ai_err_length_required: "Bitte eine Länge wählen.",
  ai_err_snapshot_failed: "Schnappschuss ging nicht – Text nicht übernommen.",
  ai_err_network: "Keine Verbindung zum Server.",
  origin_ai_draft: "KI-Entwurf",
  origin_ai_edited: "KI-Entwurf, bearbeitet",
  ai_read_only: "Du kannst dieses Projekt nur lesen – KI-Funktionen sind gesperrt.",
  ai_err_run_active: "Für dieses Buch läuft schon ein Ghostwriter-Lauf.",
  ai_err_confirm_required: "Bitte die Schätzung bestätigen.",
  ai_err_over_limit: "Die Schätzung liegt über der Kostengrenze des Buchs.",
  ai_err_nothing_to_write: "Im gewählten Umfang gibt es keine Szene zum Schreiben (Zusammenfassung fehlt oder Text ist schon da).",
  ai_err_outline_invalid: "Die KI hat keine brauchbare Gliederung geliefert – bitte nochmal versuchen.",
  ai_err_version_conflict: "Die Szene wurde inzwischen geändert – bitte erst neu laden.",
  ai_err_too_many_scenes: "Zu viele Szenen für ein Buch bzw. einen Lauf.",
  ai_err_proposal_not_found: "Der Vorschlag ist nicht mehr da.",
  run_intro: "Die KI schreibt mehrere Szenen nacheinander im Hintergrund – du kannst weiterarbeiten oder das Buch schließen. Leere Szenen werden direkt gefüllt, Szenen mit Text bekommen einen Vorschlag.",
  run_scope: "Umfang",
  run_scope_chapter: "dieses Kapitel",
  run_scope_from: "ab dieser Szene",
  run_scope_book: "ganzes Buch",
  run_skip_filled: "Szenen mit Text überspringen",
  run_limit: "Kostengrenze (Ausgabe-Tokens je Lauf)",
  run_limit_none: "keine",
  run_estimate: "Schätzung: {{scenes}} Szene(n), ca. {{out}} Ausgabe- und {{in}} Eingabe-Tokens · Modell: {{model}}",
  run_cost: "ca. {{cents}} Cent",
  run_cost_partial: "ca. {{cents}} Cent (nicht für alle Teile bekannt)",
  run_skipped: "übersprungen: {{filled}} mit Text, {{nosum}} ohne Zusammenfassung",
  run_over_limit: "Die Schätzung liegt über der Kostengrenze. Du kannst trotzdem starten – dann gilt die Grenze für diesen Lauf nicht.",
  run_start: "{{scenes}} Szene(n) schreiben – Schätzung bestätigen",
  run_start_over: "Trotzdem {{scenes}} Szene(n) schreiben",
  run_status_queued: "Wartet …",
  run_status_running: "Schreibt …",
  run_status_done: "Fertig",
  run_status_cancelled: "Abgebrochen",
  run_status_limit: "Kostengrenze erreicht",
  run_status_error: "Fehler",
  run_counts: "{{done}} von {{total}} · {{written}} geschrieben, {{proposals}} als Vorschlag, {{skipped}} übersprungen · {{words}} Wörter",
  run_current: "Gerade: „{{title}}“",
  run_tokens: "ca. {{out}} Ausgabe- / {{in}} Eingabe-Tokens",
  run_proposals_hint_one: "{{count}} Szene hatte schon Text – der Vorschlag liegt an der Szene bereit.",
  run_proposals_hint_other: "{{count}} Szenen hatten schon Text – die Vorschläge liegen an den Szenen bereit.",
  outline_open: "Gliederung aus Idee …",
  outline_title: "Gliederung aus Idee",
  outline_idea: "Idee",
  outline_hints: "Hinweise (optional)",
  outline_hints_ph: "z. B. Ich-Erzählerin, Ende offen, drei Handlungsstränge",
  outline_chapters: "Kapitel",
  outline_per_chapter: "Szenen je Kapitel",
  outline_generate: "Gliederung vorschlagen",
  outline_review: "Vorschlag: {{chapters}} Kapitel, {{scenes}} Szenen – ändern oder streichen, dann übernehmen.",
  outline_chapter_title: "Kapiteltitel",
  outline_scene_title: "Szenentitel",
  outline_remove: "Streichen",
  outline_entities: "Neue Steckbriefe: {{names}}",
  outline_apply: "Übernehmen",
  outline_empty: "Die Gliederung ist leer.",
  outline_title_missing: "Jedes Kapitel und jede Szene braucht einen Titel.",
  outline_summary_missing: "Jede Szene braucht eine Zusammenfassung – daraus schreibt die KI später.",
  proposal_ready: "KI-Vorschlag liegt bereit ({{words}} Wörter). Dein Text bleibt, bis du übernimmst.",
  proposal_ready_short: "KI-Vorschlag liegt bereit",
  proposal_view: "Ansehen",
  proposal_hide: "Ausblenden",
  interview_intro: "Interview zum Kapitel „{{chapter}}“: Die KI stellt Fragen, du antwortest – getippt oder diktiert. Daraus schreibt sie das Kapitel in deiner Stimme und erfindet nichts dazu.",
  interview_count: "{{answered}} von {{total}} Fragen beantwortet",
  interview_question: "Frage",
  interview_answer: "Antwort",
  interview_answer_ph: "Erzähl einfach – Stichworte reichen, Einzelheiten helfen.",
  interview_suggest: "Fragen vorschlagen",
  interview_more: "Weitere Fragen vorschlagen",
  interview_write: "Kapitel aus den Antworten schreiben …",
  interview_need_answer: "Mindestens eine Frage beantworten, dann kann die KI schreiben.",
  interview_confirm: "{{scenes}} Abschnitt(e) aus dem Interview schreiben, ca. {{out}} Ausgabe-Tokens · Modell: {{model}}",
  interview_conflict: "Das Interview wurde inzwischen woanders geändert (anderes Fenster oder Agent).",
  interview_save_failed: "Speichern ging nicht.",
  dictate_start: "Diktieren",
  dictate_stop: "Aufnahme beenden",
  dictate_empty: "Nichts verstanden – bitte nochmal.",
  dictate_failed: "Spracherkennung nicht erreichbar – Tippen geht immer.",
  dictate_no_mic: "Kein Mikrofon (oder nicht erlaubt).",
  ai_err_interview_empty: "Im Interview ist noch keine Frage beantwortet.",
  ai_err_interview_needs_chapter: "Aus dem Interview wird immer ein Kapitel geschrieben.",
  ai_err_questions_invalid: "Die KI hat keine brauchbaren Fragen geliefert – bitte nochmal.",
  ai_err_interview_invalid: "Fragen oder Antworten sind ungültig (zu lang oder zu viele).",
  ai_err_stt_failed: "Spracherkennung nicht erreichbar.",
  ai_share: "KI-Anteil {{n}} %",
  chat_intro: "Der Projekt-Agent kann im Chat dieses Buch lesen und Szenentext, Titel, Zusammenfassung und Perspektive einer Szene sowie Steckbriefe und neue Kapitel vorschlagen. Er ändert nichts direkt: Textvorschläge erscheinen über dem Editor, Infos-Vorschläge im Reiter „Szene“, Steckbrief-Vorschläge in der Steckbrief-Liste, neue Kapitel unter „Kapitel/Buch“ – du übernimmst oder verwirfst sie.",
  chat_agent: "Projekt-Agent: {{name}}",
  chat_no_agent: "Dieses Projekt hat keinen Projekt-Agenten. Ihn in den Projekt-Einstellungen anlegen, dann geht es hier weiter.",
  chat_tools_missing: "Dem Agenten fehlen Storyteller-Werkzeuge: {{tools}}. Ohne sie kann er das Buch nicht lesen bzw. nichts vorschlagen.",
  chat_add_tools: "Werkzeuge zuschalten",
  chat_tools_ask_admin: "Ein Admin kann sie unter Agenten → Werkzeuge zuschalten.",
  chat_start: "Chat mit dem Projekt-Agenten öffnen",
  chat_started: "Der Chat ist in einem neuen Tab offen. Diesen Einstieg dort einfügen und deine Bitte ergänzen:",
  chat_copy: "Einstieg kopieren",
  chat_copied: "Kopiert",
  chat_open_again: "Chat öffnen",
  chat_proposals_hint: "Neue Vorschläge des Agenten erscheinen hier automatisch (alle 10 Sekunden geprüft).",
  proposal_from_agent: "Vorschlag vom Agenten im Chat ({{words}} Wörter). Dein Text bleibt, bis du übernimmst.",
  proposal_note: "Notiz des Agenten: {{note}}",
  ai_err_project_agent_missing: "Dieses Projekt hat keinen Projekt-Agenten.",
  ai_err_agent_no_access: "Kein Zugriff auf den Projekt-Agenten.",
  info_proposal_title: "Vorschlag vom Agenten für diese Szene",
  info_proposal_same: "schon so",
  info_proposal_accept: "Ausgewählte übernehmen",
  ai_err_fields_invalid: "Diese Felder sind nicht (mehr) im Vorschlag.",
  ai_err_nothing_changed: "Der Vorschlag ändert nichts.",
  entity_proposal_new: "Vorschlag vom Agenten: neuer Eintrag ({{group}})",
  entity_proposal_change: "Vorschlag vom Agenten: Änderung an diesem Steckbrief",
  entity_proposal_apply: "Änderung übernehmen",
  entity_proposal_create: "Anlegen",
  entity_proposal_badge: "Vorschlag",
  ai_err_entity_not_found: "Diesen Steckbrief gibt es nicht mehr – den Vorschlag bitte verwerfen.",
  ai_err_entity_exists: "Einen Steckbrief mit diesem Namen gibt es schon.",
  ai_err_entity_invalid: "Der Steckbrief-Vorschlag ist ungültig.",
  outline_proposal_title: "Vorschlag vom Agenten: neue Kapitel (werden beim Übernehmen am Ende angehängt)",
  outline_proposal_hint: "Der Agent hat neue Kapitel vorgeschlagen – unter „Kapitel/Buch“ ansehen, bearbeiten und übernehmen.",
  outline_proposal_go: "Ansehen",
}

export type GhostTexts = typeof ghostDe
