// Oberflächentexte Deutsch (i18n-Namespace „storyteller“). Englisch: texts.en.ts, gleiche Schlüssel.

export const textsDe = {
  title: "Storyteller",
  subtitle: "Bücher und Geschichten schreiben – die KI macht nur Vorschläge, du entscheidest.",
  draft_badge: "Entwurf",
  draft_hint: "Klickbarer Entwurf: Bücher werden nur in diesem Browser gespeichert, die KI-Vorschläge sind Platzhalter.",
  project: "Projekt",
  project_pick: "Projekt wählen …",
  project_none: "Du bist in keinem Projekt. Bücher gehören immer zu einem Projekt.",
  books: "Bücher",
  books_empty: "Noch kein Buch in diesem Projekt.",
  new_book: "Neues Buch",
  sample_book: "Beispielbuch laden („Die Verwandlung“)",
  continue_last: "Weiterschreiben",
  open: "Öffnen",
  delete_book: "Löschen",
  delete_confirm: "„{{title}}“ wirklich löschen? Im Entwurf lässt sich das nicht rückgängig machen.",
  words_n: "{{n}} Wörter",
  edited_at: "bearbeitet {{when}}",
  // Neues Buch
  nb_title: "Titel",
  nb_kind: "Art",
  kind_novel: "Roman",
  kind_story: "Geschichte",
  kind_nonfiction: "Sachbuch",
  kind_learning: "Lernbuch",
  nb_language: "Sprache",
  nb_audience: "Zielgruppe",
  nb_audience_ph: "z. B. Jugendliche ab 14",
  nb_idea: "Idee (optional)",
  nb_idea_ph: "Worum geht es? 1–3 Sätze.",
  nb_create: "Buch anlegen",
  cancel: "Abbrechen",
  // Arbeitsplatz
  back_books: "Bücher",
  view_write: "Schreiben",
  view_plan: "Planen",
  view_ask: "Fragen",
  soon: "kommt bald",
  focus: "Fokusmodus (Strg+Shift+F)",
  toggle_left: "Navigator ein/aus (Strg+B)",
  toggle_right: "Kontext ein/aus (Strg+J)",
  structure: "Gliederung",
  add_scene: "Szene hinzufügen",
  add_chapter: "Kapitel hinzufügen",
  rename: "Umbenennen",
  remove_scene: "Szene löschen",
  remove_scene_confirm: "Szene „{{title}}“ löschen?",
  move_up: "Nach oben (Alt+↑)",
  move_down: "Nach unten (Alt+↓)",
  drag_hint: "Szenen lassen sich mit der Maus ziehen.",
  read_chapter: "Ganzes Kapitel lesen",
  back_to_scene: "Zurück zur Szene",
  placeholder: "Schreib los …",
  // Reiter rechts
  tab_scene: "Szene",
  tab_entity: "Steckbrief",
  tab_ai: "KI",
  tab_notes: "Notizen",
  scene_title: "Titel",
  scene_summary: "Zusammenfassung",
  scene_summary_ph: "Was passiert in dieser Szene? 1–3 Sätze.",
  scene_pov: "Perspektive",
  scene_pov_none: "– keine –",
  scene_status: "Stand",
  status_idea: "Idee",
  status_draft: "Entwurf",
  status_revised: "überarbeitet",
  status_done: "fertig",
  in_scene: "In dieser Szene",
  in_scene_none: "Keine Steckbriefe erkannt.",
  snapshots: "Schnappschüsse",
  snapshot_now: "Schnappschuss jetzt",
  snapshot_restore: "Wiederherstellen",
  snapshot_restore_confirm: "Szene auf den Stand von {{when}} zurücksetzen? Der jetzige Stand wird vorher selbst als Schnappschuss gesichert.",
  snapshots_none: "Noch keine. Vor jedem angenommenen KI-Vorschlag wird automatisch einer angelegt.",
  // Steckbriefe
  group_character: "Figuren",
  group_place: "Orte",
  group_item: "Gegenstände",
  group_term: "Begriffe",
  group_person: "Personen",
  group_source: "Quellen",
  add_entity: "Neu",
  entity_none: "Links einen Steckbrief wählen oder neu anlegen.",
  entity_name: "Name",
  entity_aliases: "Spitznamen / andere Namen",
  entity_aliases_ph: "durch Komma getrennt",
  entity_desc: "Beschreibung",
  entity_fields: "Eigenschaften",
  entity_field_key: "z. B. Augenfarbe",
  entity_field_value: "z. B. grün",
  entity_field_add: "Eigenschaft hinzufügen",
  entity_delete: "Steckbrief löschen",
  entity_delete_confirm: "Steckbrief „{{name}}“ löschen?",
  entity_new_name: "Neuer Eintrag",
  // KI
  ai_intro: "Markiere Text im Editor und wähle eine Aktion. Ohne Markierung schreibt die KI ab der Cursorposition weiter.",
  ai_rewrite: "Umschreiben",
  ai_expand: "Ausbauen",
  ai_shorten: "Kürzen",
  ai_continue: "Weiterschreiben",
  ai_placeholder_note: "Entwurf: Die KI ist hier noch ein Platzhalter und erzeugt Beispieltext.",
  ai_proposal: "Vorschlag",
  ai_accept: "Annehmen (Strg+Enter)",
  ai_reject: "Ablehnen (Esc)",
  ai_again: "Nochmal",
  ai_stale: "Die Szene wurde inzwischen geändert. Bitte neu anfordern.",
  ai_history: "Verlauf dieser Szene",
  ai_history_none: "Noch keine Vorschläge.",
  ai_state_accepted: "angenommen",
  ai_state_rejected: "abgelehnt",
  ai_model: "Modell: Standard (im Entwurf nicht aktiv)",
  notes_ph: "Freie Notizen zum Buch: Ideen, offene Fragen, Recherche …",
  // Statusleiste
  saved: "Gespeichert",
  saving: "Speichert …",
  save_failed: "Speichern fehlgeschlagen – Text bleibt im Fenster, bitte nicht schließen",
  w_scene: "Szene",
  w_chapter: "Kapitel",
  w_book: "Buch",
  words_unit: "Wörter",
  shortcuts: "Tastenkürzel",
  shortcuts_list: "Strg+B Navigator · Strg+J Kontext · Strg+Shift+F Fokus · Alt+↑/↓ Szene verschieben · Strg+Z rückgängig",
}

export type Texts = typeof textsDe
