// Oberflächentexte Englisch für KI-Modi und Ghostwriter – gleiche Schlüssel wie texts.ghost.de.ts.
import type { GhostTexts } from "./texts.ghost.de"

export const ghostEn: GhostTexts = {
  ai_mode: "AI mode",
  ai_mode_edit: "Edit",
  ai_mode_edit_hint: "Rewrite, expand, shorten or continue the selected text",
  ai_mode_scene: "Write scene",
  ai_mode_scene_hint: "The AI writes the whole scene from its summary",
  ai_mode_chapter: "Chapter/book",
  ai_mode_chapter_hint: "",
  ai_mode_interview: "Interview",
  ai_mode_interview_hint: "",
  ai_mode_chat: "In chat",
  ai_mode_chat_hint: "",
  ai_model_inherited: "as book ({{model}}})",
  ghost_intro: "The AI writes this scene from its summary, the profiles and what happened before. You watch the text appear and decide afterwards.",
  ghost_model_label: "Ghostwriter model:",
  ghost_model_default: "default",
  ghost_length: "Length",
  ghost_len_800: "short (~800 words)",
  ghost_len_1500: "medium (~1,500)",
  ghost_len_2500: "long (~2,500)",
  ghost_len_free: "words",
  ghost_style: "Style (for this book)",
  ghost_style_ph: "e.g. past tense, sober, long sentences, little dialogue",
  ghost_reject: "Discard",
  ghost_go_summary: "Go to summary",
  ghost_need_summary: "First enter a summary for the scene (tab “Scene”) – the AI writes from it.",
  ghost_has_text: "The scene already has text. The result is shown as a suggestion; your text is saved as a snapshot first.",
  ghost_estimate: "Estimate: {{sections}} section(s), ~{{out}} output and ~{{in}} input tokens · model: {{model}}",
  ghost_start: "Write scene",
  ghost_stop: "Cancel",
  ghost_writing: "Writing … {{n}} words",
  ghost_ready: "Done · {{n}} words",
  ghost_accept: "Use it",
  ghost_accept_replace: "Replace (snapshot first)",
  ghost_accepted: "Taken over. The scene is marked as AI draft until you edit it.",
  ai_err_aborted: "Cancelled.",
  ai_err_stream_incomplete: "The connection broke before the text was finished.",
  ai_err_summary_required: "First enter a summary for the scene.",
  ai_err_length_required: "Please choose a length.",
  ai_err_snapshot_failed: "Snapshot failed – text not taken over.",
  ai_err_network: "No connection to the server.",
  origin_ai_draft: "AI draft",
  origin_ai_edited: "AI draft, edited",
  ai_share: "AI share {{n}} %",
}
