// Oberflächentexte Deutsch für die Team-Knöpfe (T1e; Teil von texts.de.ts, ausgelagert wegen Länge).
// Englisch: texts.team.en.ts, gleiche Schlüssel (Typ erzwingt Vollständigkeit).

export const teamDe = {
  job_heading: "Team beauftragen",
  job_hint: "Ein Klick schickt genau einen Helfer los – ohne Chat. Das Ergebnis erscheint unten als Hinweis oder Vorschlag.",
  job_check_scene: "Szene prüfen",
  job_edit_scene: "Lektorat",
  job_critique_chapter: "Kritisch lesen",
  job_structure_chapter: "Aufbau prüfen",
  job_update_profiles: "Steckbriefe pflegen",
  job_scope_scene: "für diese Szene",
  job_scope_chapter: "für dieses Kapitel",
  job_unavailable: "Diesen Helfer gibt es in diesem Projekt nicht.",
  job_confirm: "{{label}} – „{{place}}“",
  job_estimate: "ca. {{total}} Tokens, ca. {{cents}} Cent ({{model}})",
  job_estimate_unknown: "ca. {{total}} Tokens, Kosten unbekannt ({{model}})",
  job_start: "Starten",
  job_start_over: "Trotzdem starten",
  job_cancel_confirm: "Abbrechen",
  job_running: "läuft …",
  job_queued: "wartet …",
  job_done: "fertig",
  job_error: "Fehler",
  job_cancelled: "abgebrochen",
  job_limit: "Grenze erreicht",
  job_stop: "Stoppen",
  job_cost: "{{cents}} Cent",
  job_recent: "Letzte Aufträge",
  job_open_session: "Verlauf",
  ai_err_job_busy: "Dieser Helfer arbeitet schon an diesem Buch – bitte warten, bis er fertig ist.",
  ai_err_too_many_jobs: "Es laufen schon 3 Aufträge für dieses Buch – bitte warten.",
  ai_err_helper_missing: "Diesen Helfer gibt es in diesem Projekt nicht.",
  ai_err_place_not_found: "Die Szene bzw. das Kapitel gibt es nicht mehr.",
  ai_err_job_not_active: "Der Auftrag läuft nicht mehr.",
}
