// Oberflächentexte Englisch – gleiche Schlüssel wie texts.de.ts (Typ erzwingt Vollständigkeit).
import type { Texts } from "./texts.de"
import { ghostEn } from "./texts.ghost.en"

export const textsEn: Texts = {
  title: "Storyteller",
  subtitle: "Write books and stories – the AI only suggests, you decide.",
  storage_hint: "Books live in the project folder of “{{name}}” (storyteller/books) – the project's agents can read them.",
  opening: "Opening book …",
  draft_found_one: "There is still {{count}} book from the clickable draft (in this browser only).",
  draft_found_other: "There are still {{count}} books from the clickable draft (in this browser only).",
  draft_take_over_one: "Take over {{count}} book",
  draft_take_over_other: "Take over {{count}} books",
  draft_forget_failed: "Taken over, but not removed from this browser – do not take them over a second time.",
  project: "Project",
  project_pick: "Choose project …",
  project_none: "You are not in any project. Books always belong to a project.",
  books: "Books",
  books_empty: "No book in this project yet.",
  new_book: "New book",
  sample_book: "Load sample book (“Die Verwandlung”)",
  continue_last: "Continue writing",
  open: "Open",
  delete_book: "Delete",
  delete_confirm: "Delete “{{title}}”? The book is moved to the project's trash (storyteller/trash).",
  delete_confirm_book_project: "Delete “{{title}}”? The book is moved to the trash. The project with author and helpers stays – you can delete it in the project cockpit.",
  words_n: "{{n}} words",
  edited_at: "edited {{when}}",
  nb_title: "Title",
  nb_kind: "Type",
  kind_novel: "Novel",
  kind_story: "Story",
  kind_nonfiction: "Non-fiction",
  kind_learning: "Textbook",
  nb_language: "Language",
  nb_audience: "Audience",
  nb_audience_ph: "e.g. teens 14+",
  nb_idea: "Idea (optional)",
  nb_idea_ph: "What is it about? 1–3 sentences.",
  nb_create: "Create book",
  nb_place: "Where?",
  nb_place_own: "Own project with writing team (recommended)",
  nb_place_own_hint: "Creates a new project just for this book – with an author for the chat and seven helpers (plausibility, research, editor, critic, creative, structure, profiles). All use the book's model.",
  nb_place_current: "In project “{{name}}”",
  nb_place_current_hint: "The book goes into the selected project. Its project agent answers in the chat.",
  nb_creating: "Creating book project with writing team …",
  project_none_can_create: "You are not in any project yet. Create a book – it gets its own project with a writing team.",
  err_no_model: "No model chosen and no HydraHive default model set (Settings → LLM).",
  err_capability_denied: "You are not allowed to create books as their own project. An admin can grant it.",
  cancel: "Cancel",
  back_books: "Books",
  view_write: "Write",
  view_plan: "Plan",
  view_ask: "Ask",
  soon: "coming soon",
  focus: "Focus mode (Ctrl+Shift+F)",
  toggle_left: "Toggle navigator (Ctrl+B)",
  toggle_right: "Toggle context (Ctrl+J)",
  structure: "Outline",
  add_scene: "Add scene",
  add_chapter: "Add chapter",
  rename: "Rename",
  remove_scene: "Delete scene",
  remove_scene_confirm: "Delete scene “{{title}}”? Text, snapshots and an open proposal are moved to the project's trash (storyteller/trash).",
  remove_scene_last: "The last scene of a chapter stays.",
  move_up: "Move up (Alt+↑)",
  move_down: "Move down (Alt+↓)",
  drag_hint: "Scenes can be dragged with the mouse.",
  read_chapter: "Read whole chapter",
  back_to_scene: "Back to scene",
  placeholder: "Start writing …",
  tab_scene: "Scene",
  tab_entity: "Profile",
  tab_ai: "AI",
  tab_notes: "Notes",
  scene_title: "Title",
  scene_summary: "Summary",
  scene_summary_ph: "What happens in this scene? 1–3 sentences.",
  scene_pov: "Point of view",
  scene_pov_none: "– none –",
  scene_status: "Status",
  status_idea: "Idea",
  status_draft: "Draft",
  status_revised: "Revised",
  status_done: "Done",
  in_scene: "In this scene",
  in_scene_none: "No profiles detected.",
  snapshots: "Snapshots",
  snapshot_now: "Snapshot now",
  snapshot_restore: "Restore",
  snapshot_restore_confirm: "Reset the scene to {{when}}? The current state is saved as a snapshot first.",
  snapshots_none: "None yet. One is created automatically before every accepted AI suggestion and before restoring.",
  group_character: "Characters",
  group_place: "Places",
  group_item: "Items",
  group_term: "Terms",
  group_person: "People",
  group_source: "Sources",
  add_entity: "New",
  entity_none: "Pick a profile on the left or create one.",
  entity_name: "Name",
  entity_aliases: "Nicknames / other names",
  entity_aliases_ph: "comma separated",
  entity_desc: "Description",
  entity_fields: "Properties",
  entity_field_key: "e.g. eye colour",
  entity_field_value: "e.g. green",
  entity_field_add: "Add property",
  entity_delete: "Delete profile",
  entity_delete_confirm: "Delete profile “{{name}}”?",
  entity_new_name: "New entry",
  ai_intro: "Select text in the editor and pick an action. Without a selection the AI continues at the cursor.",
  ai_rewrite: "Rewrite",
  ai_expand: "Expand",
  ai_shorten: "Shorten",
  ai_continue: "Continue",
  ai_working: "The AI is writing a suggestion …",
  ai_err_selection_required: "Select some text first or put the cursor into a paragraph.",
  ai_err_ai_busy: "An AI request for this book is already running – please wait a moment.",
  ai_err_rate_limited: "Too many AI requests – please wait a minute.",
  ai_err_llm_empty: "The model returned no text. Try again or pick another model.",
  ai_err_not_authenticated: "You are no longer logged in.",
  ai_err_project_read_only: "You only have read access in this project.",
  ai_err_llm_failed: "The AI is not reachable right now: {{message}}",
  ai_err_snapshot: "Snapshot failed – suggestion not inserted.",
  ai_model_label: "Model:",
  ai_model_standard: "Default ({{model}})",
  ai_model_change: "change",
  ai_model_use_standard: "Use the HydraHive default ({{model}})",
  ai_models_failed: "Could not load models: {{error}}",
  ai_proposal: "Suggestion",
  ai_accept: "Accept (Ctrl+Enter)",
  ai_reject: "Reject (Esc)",
  ai_again: "Again",
  ai_stale: "The scene has changed in the meantime. Please request again.",
  ai_history: "History for this scene",
  ai_history_none: "No suggestions yet.",
  ai_state_accepted: "accepted",
  ai_state_rejected: "rejected",
  notes_ph: "Free notes for the book: ideas, open questions, research …",
  saved: "Saved",
  saving: "Saving …",
  save_failed: "Saving failed – text stays in this window, please do not close it",
  save_retry: "retry",
  save_conflict: "Conflict – please decide",
  err_title_required: "title must not be empty",
  err_entity_name_required: "profile needs a name",
  err_text_too_long: "scene is too long (max. 200 KB)",
  err_project_read_only: "you only have read access in this project",
  err_too_many_scenes: "too many scenes",
  // Project + conflict
  project_badge_title: "Project: {{name}} – the book lives in its folder",
  conflict_title: "Changed in the meantime",
  conflict_scene: "The scene “{{title}}” was changed in the meantime",
  conflict_structure: "The outline or the profiles were changed in the meantime",
  conflict_book: "Title, notes or model of the book were changed in the meantime",
  conflict_by: "(by you in another window or by an agent).",
  conflict_safe_scene: "Nothing gets lost: the version you do not take is kept as a snapshot of the scene.",
  conflict_safe_other: "“Reload” takes the other state; “Keep my version” saves yours on top.",
  conflict_reload: "Reload",
  conflict_keep: "Keep my version",
  w_scene: "Scene",
  w_chapter: "Chapter",
  w_book: "Book",
  words_unit: "words",
  shortcuts: "Shortcuts",
  shortcuts_list: "Ctrl+B navigator · Ctrl+J context · Ctrl+Shift+F focus · Alt+↑/↓ move scene · Ctrl+Z undo",
  ...ghostEn,
}
