// UI texts English for "nothing gets lost" (A2 proposal history, A3 trash; part of texts.en.ts). Same keys as texts.keep.de.ts.
import type { keepDe } from "./texts.keep.de"

export const keepEn: typeof keepDe = {
  history_title: "Earlier proposals",
  history_none: "None. Replaced and discarded proposals end up here and can be brought back.",
  history_kind_text: "Text",
  history_kind_info: "Info",
  history_from: "by {{who}}",
  history_from_agent: "agent",
  history_from_run: "ghostwriter run",
  history_words: "{{n}} words",
  history_discarded: "discarded",
  history_replaced_by: "replaced by {{who}}",
  history_restore: "Bring back",
  history_restored_over: "set aside (an older one was brought back)",
  proposal_from_named: "Proposal by {{who}} ({{words}} words). Your text stays until you accept.",
  replaced_hint: "Replaces a proposal by {{who}} – it is kept under “Earlier proposals” (tab “Scene”).",
  trash_title: "Trash",
  trash_scenes_none: "No deleted scenes.",
  trash_books_none: "No deleted books.",
  trash_deleted_at: "deleted {{when}}",
  trash_restore: "Restore",
  trash_back_original: "goes back to its old place in “{{chapter}}”",
  trash_back_end: "goes to the end of the first chapter (its old chapter is gone)",
  trash_restored_original: "“{{title}}” is back at its old place.",
  trash_restored_end: "“{{title}}” is back – at the end of the first chapter.",
  trash_book_restored: "“{{title}}” is back in the list.",
  trash_scenes_n: "{{n}} scene(s), {{words}} words",
  trash_moved: "moved to a project of its own – backup (the book lives on in the new project)",
  ai_err_scene_exists: "This scene is already back in the book.",
  ai_err_book_exists: "This book is already back in the list.",
  ai_err_trash_entry_not_found: "The entry is no longer in the trash.",
  ai_err_trash_entry_broken: "The entry in the trash is incomplete.",
  // A5c chapter summary
  chapter_summary_title: "Chapter “{{title}}”",
  chapter_summary_ph: "What happens in this chapter? (3–5 sentences – replaces the single scenes of older chapters in the ghostwriter's memory)",
  chapter_summary_hint: "Saved when you leave the field. Without a chapter summary the ghostwriter remembers every scene on its own.",
  chapter_summary_saving: "Saving …",
  chapter_summary_generate: "Generate summary",
  chapter_summary_generate_hint: "The AI condenses the summaries of this chapter's scenes. Nothing is saved until you accept.",
  chapter_summary_proposal: "AI proposal – not saved yet",
  chapter_summary_accept: "Accept",
  chapter_summary_discard: "Discard",
  chapter_summary_conflict: "The chapter summary was changed elsewhere in the meantime. Your text is still in the field – it will be saved when you leave it again.",
  chapter_summary_err_summaries_required: "The scenes of this chapter have no summaries yet – the chapter summary is built from them.",
  chapter_summary_err_ai_busy: "An AI request for this book is already running – please wait.",
  chapter_summary_err_rate_limited: "Too many AI requests – please wait a minute.",
  chapter_summary_err_llm_empty: "The model returned no text.",
}
