// Oberflächentexte Deutsch für „Nichts geht verloren“ (A2 Vorschlags-Verlauf, A3 Papierkorb; Teil von texts.de.ts).
// Englisch: texts.keep.en.ts, gleiche Schlüssel (Typ erzwingt Vollständigkeit).

export const keepDe = {
  history_title: "Frühere Vorschläge",
  history_none: "Keine. Ersetzte und verworfene Vorschläge landen hier und lassen sich zurückholen.",
  history_kind_text: "Text",
  history_kind_info: "Infos",
  history_from: "von {{who}}",
  history_from_agent: "Agent",
  history_from_run: "Ghostwriter-Lauf",
  history_words: "{{n}} Wörter",
  history_discarded: "verworfen",
  history_replaced_by: "ersetzt durch {{who}}",
  history_restore: "Zurückholen",
  proposal_from_named: "Vorschlag von {{who}} ({{words}} Wörter). Dein Text bleibt, bis du übernimmst.",
  replaced_hint: "Ersetzt einen Vorschlag von {{who}} – der liegt unter „Frühere Vorschläge“ (Reiter „Szene“).",
  trash_title: "Papierkorb",
  trash_scenes_none: "Keine gelöschten Szenen.",
  trash_books_none: "Keine gelöschten Bücher.",
  trash_deleted_at: "gelöscht {{when}}",
  trash_restore: "Wiederherstellen",
  trash_back_original: "kehrt an ihre alte Stelle in „{{chapter}}“ zurück",
  trash_back_end: "kommt ans Ende des ersten Kapitels (das alte Kapitel gibt es nicht mehr)",
  trash_restored_original: "„{{title}}“ ist wieder an ihrer alten Stelle.",
  trash_restored_end: "„{{title}}“ ist wieder da – am Ende des ersten Kapitels.",
  trash_book_restored: "„{{title}}“ ist wieder in der Liste.",
  trash_scenes_n: "{{n}} Szene(n), {{words}} Wörter",
  trash_moved: "in ein eigenes Projekt umgezogen – Sicherung (das Buch lebt im neuen Projekt weiter)",
  ai_err_scene_exists: "Diese Szene ist schon wieder im Buch.",
  ai_err_book_exists: "Dieses Buch ist schon wieder in der Liste.",
  ai_err_trash_entry_not_found: "Der Eintrag ist nicht mehr im Papierkorb.",
  ai_err_trash_entry_broken: "Der Eintrag im Papierkorb ist unvollständig.",
}
