// Oberflächentexte Deutsch (i18n-Namespace „storyteller“). Englisch: texts.en.ts, gleiche Schlüssel.

import { ghostDe } from "./texts.ghost.de"
import { keepDe } from "./texts.keep.de"
import { teamDe } from "./texts.team.de"

export const textsDe = {
  title: "Storyteller",
  subtitle: "Bücher und Geschichten schreiben – die KI macht nur Vorschläge, du entscheidest.",
  storage_hint: "Bücher liegen im Projektordner von „{{name}}“ (storyteller/books) – Agenten des Projekts können sie lesen.",
  opening: "Buch wird geöffnet …",
  draft_found_one: "Hier liegt noch {{count}} Buch aus dem klickbaren Entwurf (nur in diesem Browser).",
  draft_found_other: "Hier liegen noch {{count}} Bücher aus dem klickbaren Entwurf (nur in diesem Browser).",
  draft_take_over_one: "{{count}} Buch übernehmen",
  draft_take_over_other: "{{count}} Bücher übernehmen",
  draft_forget_failed: "Übernommen, aber im Browser nicht gelöscht – beim nächsten Mal nicht noch einmal übernehmen.",
  project: "Projekt",
  project_pick: "Projekt wählen …",
  project_none: "Du bist in keinem Projekt. Bücher gehören immer zu einem Projekt.",
  books: "Bücher",
  books_empty: "Noch kein Buch in diesem Projekt.",
  new_book: "Neues Buch",
  sample_book: "Beispielbuch laden („Die Verwandlung“)",
  continue_last: "Weiterschreiben",
  open: "Öffnen",
  delete_book: "Löschen",
  delete_confirm: "„{{title}}“ löschen? Das Buch wandert in den Papierkorb des Projekts (storyteller/trash).",
  delete_confirm_book_project: "„{{title}}“ löschen? Das Buch wandert in den Papierkorb. Das Projekt mit Autor und Helfern bleibt bestehen – löschen kannst du es im Projekt-Cockpit.",
  words_n: "{{n}} Wörter",
  edited_at: "bearbeitet {{when}}",
  // Neues Buch
  nb_title: "Titel",
  nb_kind: "Art",
  kind_novel: "Roman",
  kind_story: "Geschichte",
  kind_nonfiction: "Sachbuch",
  kind_learning: "Lernbuch",
  nb_language: "Sprache",
  nb_audience: "Zielgruppe",
  nb_audience_ph: "z. B. Jugendliche ab 14",
  nb_idea: "Idee (optional)",
  nb_idea_ph: "Worum geht es? 1–3 Sätze.",
  nb_create: "Buch anlegen",
  nb_place: "Wohin?",
  nb_place_own: "Eigenes Projekt mit Schreib-Team (empfohlen)",
  nb_place_own_hint: "Legt ein neues Projekt nur für dieses Buch an – mit einem Autor für den Chat und sieben Helfern (Plausibilität, Recherche, Lektor, Kritiker, Kreativ, Struktur, Steckbriefe). Alle nutzen das Modell des Buchs.",
  nb_place_current: "Im Projekt „{{name}}“",
  nb_place_current_hint: "Das Buch kommt in das gewählte Projekt. Im Chat antwortet dessen Projekt-Agent.",
  nb_creating: "Buch-Projekt mit Schreib-Team wird angelegt …",
  project_none_can_create: "Du bist noch in keinem Projekt. Lege ein Buch an – es bekommt ein eigenes Projekt mit Schreib-Team.",
  err_no_model: "Kein Modell gewählt und kein HydraHive-Standardmodell eingestellt (Einstellungen → LLM).",
  err_model_unavailable: "Das gewählte Modell ist auf diesem Server gerade nicht verfügbar (nicht in der Modell-Liste). Bitte ein anderes Modell wählen – beim Umziehen im Buch unter „Einstellungen“.",
  move_book: "In eigenes Projekt umziehen",
  move_hint: "Das Buch bekommt ein eigenes Projekt mit Schreib-Team (Autor und Helfer).",
  move_confirm: "„{{title}}“ in ein eigenes Projekt mit Schreib-Team umziehen?\n\nSzenen, Schnappschüsse, Vorschläge, Interviews und Hinweise ziehen mit. Hier im Projekt bleibt eine Sicherung im Papierkorb. Alte Chats mit dem Projekt-Agenten bleiben hier.",
  err_already_book_project: "Das Buch hat schon ein eigenes Projekt.",
  err_run_active: "Für dieses Buch läuft gerade ein Ghostwriter-Lauf – bitte warten, bis er fertig ist.",
  err_job_active: "Ein Helfer arbeitet gerade an diesem Buch – bitte warten, bis er fertig ist.",
  err_move_check_failed: "Die Kopie war nicht vollständig – das Buch bleibt, wo es ist. Bitte nochmal versuchen.",
  err_capability_denied: "Dir fehlt die Freigabe, Bücher als eigenes Projekt anzulegen. Ein Admin kann sie erteilen.",
  cancel: "Abbrechen",
  // Arbeitsplatz
  back_books: "Bücher",
  view_write: "Schreiben",
  view_plan: "Planen",
  view_ask: "Fragen",
  soon: "kommt bald",
  focus: "Fokusmodus (Strg+Shift+F)",
  toggle_left: "Navigator ein/aus (Strg+B)",
  toggle_right: "Kontext ein/aus (Strg+J)",
  structure: "Gliederung",
  add_scene: "Szene hinzufügen",
  add_chapter: "Kapitel hinzufügen",
  rename: "Umbenennen",
  move_up: "Nach oben (Alt+↑)",
  move_down: "Nach unten (Alt+↓)",
  drag_hint: "Szenen lassen sich mit der Maus ziehen.",
  drag_hint_section: "Abschnitte lassen sich mit der Maus ziehen.",
  add_section: "Abschnitt hinzufügen",
  read_chapter: "Ganzes Kapitel lesen",
  back_to_scene: "Zurück zur Szene",
  placeholder: "Schreib los …",
  // Reiter rechts
  tab_scene: "Szene",
  tab_entity: "Steckbrief",
  tab_ai: "KI",
  tab_notes: "Notizen",
  tab_team: "Team",
  team_scope: "Anzeigen für",
  team_scope_scene: "Szene",
  team_scope_chapter: "Kapitel",
  team_scope_book: "Buch",
  team_empty: "Noch nichts vom Team. Hier legen die Helfer ihre Hinweise (Widersprüche, Stil, Handlung) und Notizen (Recherche mit Quellen, Ideen) ab – beauftragt vom Autor im Chat.",
  team_kind_hint: "Hinweis",
  team_kind_note: "Notiz",
  team_done: "Erledigt",
  team_dismiss: "Verwerfen",
  team_go_scene: "Zur Szene",
  team_scene_gone: "Szene gelöscht",
  team_open_n: "{{n}} offene Hinweise vom Team",
  scene_title: "Titel",
  scene_summary: "Zusammenfassung",
  scene_summary_ph: "Was passiert in dieser Szene? 1–3 Sätze.",
  scene_pov: "Perspektive",
  scene_pov_none: "– keine –",
  scene_status: "Stand",
  status_idea: "Idee",
  status_draft: "Entwurf",
  status_revised: "überarbeitet",
  status_done: "fertig",
  in_scene: "In dieser Szene",
  in_scene_none: "Keine Steckbriefe erkannt.",
  snapshots: "Schnappschüsse",
  snapshot_now: "Schnappschuss jetzt",
  snapshot_restore: "Wiederherstellen",
  snapshot_restore_confirm: "Szene auf den Stand von {{when}} zurücksetzen? Der jetzige Stand wird vorher selbst als Schnappschuss gesichert.",
  snapshots_none: "Noch keine. Vor jedem angenommenen KI-Vorschlag und vor dem Wiederherstellen wird automatisch einer angelegt.",
  // Steckbriefe
  group_character: "Figuren",
  group_place: "Orte",
  group_item: "Gegenstände",
  group_term: "Begriffe",
  group_person: "Personen",
  group_source: "Quellen",
  add_entity: "Neu",
  entity_none: "Links einen Steckbrief wählen oder neu anlegen.",
  entity_name: "Name",
  entity_aliases: "Spitznamen / andere Namen",
  entity_aliases_ph: "durch Komma getrennt",
  entity_desc: "Beschreibung",
  entity_fields: "Eigenschaften",
  entity_field_key: "z. B. Augenfarbe",
  entity_field_value: "z. B. grün",
  entity_field_add: "Eigenschaft hinzufügen",
  entity_delete: "Steckbrief löschen",
  entity_delete_confirm: "Steckbrief „{{name}}“ löschen?",
  entity_new_name: "Neuer Eintrag",
  // KI
  ai_intro: "Markiere Text im Editor und wähle eine Aktion. Ohne Markierung schreibt die KI ab der Cursorposition weiter.",
  ai_rewrite: "Umschreiben",
  ai_expand: "Ausbauen",
  ai_shorten: "Kürzen",
  ai_continue: "Weiterschreiben",
  ai_working: "Die KI schreibt einen Vorschlag …",
  ai_err_selection_required: "Bitte erst Text markieren oder den Cursor in einen Absatz setzen.",
  ai_err_ai_busy: "Für dieses Buch läuft schon eine KI-Anfrage – bitte kurz warten.",
  ai_err_rate_limited: "Zu viele KI-Anfragen – bitte eine Minute warten.",
  ai_err_llm_empty: "Das Modell hat keinen Text geliefert. Nochmal versuchen oder anderes Modell wählen.",
  ai_err_not_authenticated: "Nicht mehr angemeldet.",
  ai_err_project_read_only: "Du hast in diesem Projekt nur Leserechte.",
  ai_err_llm_failed: "Die KI ist gerade nicht erreichbar: {{message}}",
  ai_err_snapshot: "Schnappschuss ging nicht – Vorschlag nicht eingesetzt.",
  ai_model_label: "Modell:",
  ai_model_standard: "Standard ({{model}})",
  ai_model_change: "ändern",
  ai_model_use_standard: "HydraHive-Standard verwenden ({{model}})",
  ai_models_failed: "Modelle konnten nicht geladen werden: {{error}}",
  ai_proposal: "Vorschlag",
  ai_accept: "Annehmen (Strg+Enter)",
  ai_reject: "Ablehnen (Esc)",
  ai_again: "Nochmal",
  ai_stale: "Die Szene wurde inzwischen geändert. Bitte neu anfordern.",
  ai_history: "Verlauf dieser Szene",
  ai_history_none: "Noch keine Vorschläge.",
  ai_state_accepted: "angenommen",
  ai_state_rejected: "abgelehnt",
  notes_ph: "Freie Notizen zum Buch: Ideen, offene Fragen, Recherche …",
  // Statusleiste
  saved: "Gespeichert",
  saving: "Speichert …",
  save_failed: "Speichern fehlgeschlagen – Text bleibt im Fenster, bitte nicht schließen",
  save_retry: "nochmal",
  save_conflict: "Konflikt – bitte entscheiden",
  err_title_required: "Titel darf nicht leer sein",
  err_entity_name_required: "Steckbrief braucht einen Namen",
  err_text_too_long: "Szene ist zu lang (max. 200 KB)",
  err_project_read_only: "du hast in diesem Projekt nur Leserechte",
  err_too_many_scenes: "zu viele Szenen",
  // Projekt + Konflikt
  project_badge_title: "Projekt: {{name}} – das Buch liegt in dessen Ordner",
  conflict_title: "Inzwischen geändert",
  conflict_scene: "Die Szene „{{title}}“ wurde inzwischen geändert",
  conflict_structure: "Die Gliederung oder die Steckbriefe wurden inzwischen geändert",
  conflict_book: "Titel, Notizen oder Modell des Buchs wurden inzwischen geändert",
  conflict_by: "(von dir in einem anderen Fenster oder von einem Agenten).",
  conflict_safe_scene: "Es geht nichts verloren: Die Fassung, die du nicht nimmst, wird als Schnappschuss der Szene gesichert.",
  conflict_safe_other: "„Neu laden“ übernimmt den anderen Stand; „Meine Fassung behalten“ speichert deinen darüber.",
  conflict_reload: "Neu laden",
  conflict_keep: "Meine Fassung behalten",
  w_scene: "Szene",
  w_chapter: "Kapitel",
  w_book: "Buch",
  words_unit: "Wörter",
  shortcuts: "Tastenkürzel",
  shortcuts_list: "Strg+B Navigator · Strg+J Kontext · Strg+Shift+F Fokus · Alt+↑/↓ Szene verschieben · Strg+Z rückgängig",
  ...ghostDe,
  ...teamDe,
  ...keepDe,
}

export type Texts = typeof textsDe
