// Oberflächentexte Deutsch für „Nichts geht verloren“ (A2 Vorschlags-Verlauf, A3 Papierkorb; Teil von texts.de.ts).
// Englisch: texts.keep.en.ts, gleiche Schlüssel (Typ erzwingt Vollständigkeit).

export const keepDe = {
  history_title: "Frühere Vorschläge",
  history_none: "Keine. Ersetzte und verworfene Vorschläge landen hier und lassen sich zurückholen.",
  history_kind_text: "Text",
  history_kind_info: "Infos",
  history_from: "von {{who}}",
  history_from_agent: "Agent",
  history_from_run: "Ghostwriter-Lauf",
  history_words: "{{n}} Wörter",
  history_discarded: "verworfen",
  history_replaced_by: "ersetzt durch {{who}}",
  history_restore: "Zurückholen",
  history_restored_over: "beiseitegelegt (ein älterer wurde zurückgeholt)",
  proposal_from_named: "Vorschlag von {{who}} ({{words}} Wörter). Dein Text bleibt, bis du übernimmst.",
  replaced_hint: "Ersetzt einen Vorschlag von {{who}} – der liegt unter „Frühere Vorschläge“ (Reiter „Szene“).",
  trash_title: "Papierkorb",
  trash_scenes_none: "Keine gelöschten Szenen.",
  trash_books_none: "Keine gelöschten Bücher.",
  trash_deleted_at: "gelöscht {{when}}",
  trash_restore: "Wiederherstellen",
  trash_back_original: "kehrt an ihre alte Stelle in „{{chapter}}“ zurück",
  trash_back_end: "kommt ans Ende des ersten Kapitels (das alte Kapitel gibt es nicht mehr)",
  trash_restored_original: "„{{title}}“ ist wieder an ihrer alten Stelle.",
  trash_restored_end: "„{{title}}“ ist wieder da – am Ende des ersten Kapitels.",
  trash_book_restored: "„{{title}}“ ist wieder in der Liste.",
  trash_scenes_n: "{{n}} Szene(n), {{words}} Wörter",
  trash_moved: "in ein eigenes Projekt umgezogen – Sicherung (das Buch lebt im neuen Projekt weiter)",
  ai_err_scene_exists: "Diese Szene ist schon wieder im Buch.",
  ai_err_book_exists: "Dieses Buch ist schon wieder in der Liste.",
  ai_err_trash_entry_not_found: "Der Eintrag ist nicht mehr im Papierkorb.",
  ai_err_trash_entry_broken: "Der Eintrag im Papierkorb ist unvollständig.",
  // A5c Kapitel-Zusammenfassung
  chapter_summary_title: "Kapitel „{{title}}“",
  chapter_summary_ph: "Worum geht es in diesem Kapitel? (3–5 Sätze – ersetzt im Gedächtnis des Ghostwriters die einzelnen Szenen älterer Kapitel)",
  chapter_summary_hint: "Wird beim Verlassen des Felds gespeichert. Ohne Kapitel-Zusammenfassung merkt sich der Ghostwriter jede Szene einzeln.",
  chapter_summary_saving: "Wird gespeichert …",
  chapter_summary_generate: "Zusammenfassung erzeugen",
  chapter_summary_generate_hint: "Die KI fasst die Zusammenfassungen der Szenen dieses Kapitels zusammen. Gespeichert wird erst, wenn du übernimmst.",
  chapter_summary_proposal: "Vorschlag der KI – noch nicht gespeichert",
  chapter_summary_accept: "Übernehmen",
  chapter_summary_discard: "Verwerfen",
  chapter_summary_conflict: "Die Kapitel-Zusammenfassung wurde inzwischen woanders geändert. Dein Text steht noch im Feld – beim nächsten Verlassen wird er gespeichert.",
  chapter_summary_err_summaries_required: "Die Szenen dieses Kapitels haben noch keine Zusammenfassungen – daraus entsteht die Kapitel-Zusammenfassung.",
  chapter_summary_err_ai_busy: "Für dieses Buch läuft schon eine KI-Anfrage – bitte warten.",
  chapter_summary_err_rate_limited: "Zu viele KI-Anfragen – bitte eine Minute warten.",
  chapter_summary_err_llm_empty: "Das Modell hat keinen Text geliefert.",
}
