// Oberflächentexte Englisch für KI-Modi und Ghostwriter – gleiche Schlüssel wie texts.ghost.de.ts.
import type { GhostTexts } from "./texts.ghost.de"

export const ghostEn: GhostTexts = {
  ai_mode: "AI mode",
  ai_mode_edit: "Edit",
  ai_mode_edit_hint: "Rewrite, expand, shorten or continue the selected text",
  ai_mode_scene: "Write scene",
  ai_mode_scene_hint: "The AI writes the whole scene from its summary",
  ai_mode_chapter: "Chapter/book",
  ai_mode_chapter_hint: "Write a chapter, everything from here or the whole book in the background",
  ai_mode_interview: "Interview",
  ai_mode_interview_hint: "The AI asks, you tell (type or dictate) – the chapter is written from it in your voice",
  ai_mode_chat: "In chat",
  ai_mode_chat_hint: "Work on the book with the project agent in chat – it leaves text as a proposal",
  ai_model_inherited: "as book ({{model}}})",
  ghost_intro: "The AI writes this scene from its summary, the profiles and what happened before. You watch the text appear and decide afterwards.",
  ghost_model_label: "Ghostwriter model:",
  ghost_model_default: "default",
  ghost_length: "Length",
  ghost_len_800: "short (~800 words)",
  ghost_len_1500: "medium (~1,500)",
  ghost_len_2500: "long (~2,500)",
  ghost_len_free: "words",
  ghost_style: "Style (for this book)",
  ghost_style_ph: "e.g. past tense, sober, long sentences, little dialogue",
  ghost_reject: "Discard",
  ghost_go_summary: "Go to summary",
  ghost_need_summary: "First enter a summary for the scene (tab “Scene”) – the AI writes from it.",
  ghost_has_text: "The scene already has text. The result is shown as a suggestion; your text is saved as a snapshot first.",
  ghost_estimate: "Estimate: {{sections}} section(s), ~{{out}} output and ~{{in}} input tokens · model: {{model}}",
  ghost_start: "Write scene",
  ghost_stop: "Cancel",
  ghost_writing: "Writing … {{n}} words",
  ghost_ready: "Done · {{n}} words",
  ghost_accept: "Use it",
  ghost_accept_replace: "Replace (snapshot first)",
  ghost_accepted: "Taken over. The scene is marked as AI draft until you edit it.",
  ai_err_aborted: "Cancelled.",
  ai_err_stream_incomplete: "The connection broke before the text was finished.",
  ai_err_summary_required: "First enter a summary for the scene.",
  ai_err_length_required: "Please choose a length.",
  ai_err_snapshot_failed: "Snapshot failed – text not taken over.",
  ai_err_network: "No connection to the server.",
  origin_ai_draft: "AI draft",
  origin_ai_edited: "AI draft, edited",
  ai_read_only: "You can only read this project – AI functions are locked.",
  ai_err_run_active: "A ghostwriter run is already active for this book.",
  ai_err_confirm_required: "Please confirm the estimate.",
  ai_err_over_limit: "The estimate is above the book's cost limit.",
  ai_err_nothing_to_write: "No scene to write in this range (summary missing or text already there).",
  ai_err_outline_invalid: "The AI did not return a usable outline – please try again.",
  ai_err_version_conflict: "The scene has changed in the meantime – please reload first.",
  ai_err_too_many_scenes: "Too many scenes for a book or a run.",
  ai_err_proposal_not_found: "The suggestion is gone.",
  run_intro: "The AI writes several scenes one after another in the background – you can keep working or close the book. Empty scenes are filled directly, scenes with text get a suggestion.",
  run_scope: "Range",
  run_scope_chapter: "this chapter",
  run_scope_from: "from this scene",
  run_scope_book: "whole book",
  run_skip_filled: "Skip scenes that have text",
  run_limit: "Cost limit (output tokens per run)",
  run_limit_none: "none",
  run_estimate: "Estimate: {{scenes}} scene(s), approx. {{out}} output and {{in}} input tokens · model: {{model}}",
  run_cost: "approx. {{cents}} cents",
  run_cost_partial: "approx. {{cents}} cents (not known for all parts)",
  run_skipped: "skipped: {{filled}} with text, {{nosum}} without summary",
  run_over_limit: "The estimate is above the cost limit. You can still start – the limit then does not apply to this run.",
  run_start: "Write {{scenes}} scene(s) – confirm estimate",
  run_start_over: "Write {{scenes}} scene(s) anyway",
  run_status_queued: "Waiting …",
  run_status_running: "Writing …",
  run_status_done: "Done",
  run_status_cancelled: "Cancelled",
  run_status_limit: "Cost limit reached",
  run_status_error: "Error",
  run_counts: "{{done}} of {{total}} · {{written}} written, {{proposals}} as suggestion, {{skipped}} skipped · {{words}} words",
  run_current: "Now: “{{title}}”",
  run_tokens: "approx. {{out}} output / {{in}} input tokens",
  run_proposals_hint_one: "{{count}} scene already had text – the suggestion is waiting at the scene.",
  run_proposals_hint_other: "{{count}} scenes already had text – the suggestions are waiting at the scenes.",
  outline_open: "Outline from idea …",
  outline_title: "Outline from idea",
  outline_idea: "Idea",
  outline_hints: "Hints (optional)",
  outline_hints_ph: "e.g. first-person narrator, open ending, three plot lines",
  outline_chapters: "Chapters",
  outline_per_chapter: "Scenes per chapter",
  outline_generate: "Suggest outline",
  outline_review: "Suggestion: {{chapters}} chapters, {{scenes}} scenes – edit or remove, then apply.",
  outline_chapter_title: "Chapter title",
  outline_scene_title: "Scene title",
  outline_remove: "Remove",
  outline_entities: "New profiles: {{names}}",
  outline_apply: "Apply",
  outline_empty: "The outline is empty.",
  outline_title_missing: "Every chapter and scene needs a title.",
  outline_summary_missing: "Every scene needs a summary – the AI writes from it later.",
  proposal_ready: "AI suggestion ready ({{words}} words). Your text stays until you apply it.",
  proposal_ready_short: "AI suggestion ready",
  proposal_view: "View",
  proposal_hide: "Hide",
  interview_intro: "Interview for the chapter “{{chapter}}”: the AI asks questions, you answer – typed or dictated. It then writes the chapter in your voice and adds nothing you didn't say.",
  interview_count: "{{answered}} of {{total}} questions answered",
  interview_question: "Question",
  interview_answer: "Answer",
  interview_answer_ph: "Just tell it – keywords are fine, details help.",
  interview_suggest: "Suggest questions",
  interview_more: "Suggest more questions",
  interview_write: "Write the chapter from the answers …",
  interview_need_answer: "Answer at least one question, then the AI can write.",
  interview_confirm: "Write {{scenes}} section(s) from the interview, approx. {{out}} output tokens · model: {{model}}",
  interview_conflict: "The interview was changed elsewhere in the meantime (another window or agent).",
  interview_save_failed: "Saving failed.",
  dictate_start: "Dictate",
  dictate_stop: "Stop recording",
  dictate_empty: "Nothing understood – please try again.",
  dictate_failed: "Speech recognition not reachable – typing always works.",
  dictate_no_mic: "No microphone (or not allowed).",
  ai_err_interview_empty: "No interview question has been answered yet.",
  ai_err_interview_needs_chapter: "The interview always writes one chapter.",
  ai_err_questions_invalid: "The AI did not return usable questions – please try again.",
  ai_err_interview_invalid: "Questions or answers are invalid (too long or too many).",
  ai_err_stt_failed: "Speech recognition not reachable.",
  ai_share: "AI share {{n}} %",
  chat_intro: "In chat, the project agent can read this book and propose scene text, a scene's title, summary and point of view, and profiles. It changes nothing directly: text proposals appear above the editor, info proposals in the “Scene” tab, profile proposals in the profile list – you accept or discard them.",
  chat_agent: "Project agent: {{name}}",
  chat_no_agent: "This project has no project agent. Create one in the project settings, then continue here.",
  chat_tools_missing: "The agent is missing Storyteller tools: {{tools}}. Without them it cannot read the book or propose text.",
  chat_add_tools: "Enable tools",
  chat_tools_ask_admin: "An admin can enable them under Agents → Tools.",
  chat_start: "Open chat with the project agent",
  chat_started: "The chat is open in a new tab. Paste this opening there and add your request:",
  chat_copy: "Copy opening",
  chat_copied: "Copied",
  chat_open_again: "Open chat",
  chat_proposals_hint: "New proposals from the agent appear here automatically (checked every 10 seconds).",
  proposal_from_agent: "Proposal from the agent in chat ({{words}} words). Your text stays until you accept.",
  proposal_note: "Agent's note: {{note}}",
  ai_err_project_agent_missing: "This project has no project agent.",
  ai_err_agent_no_access: "No access to the project agent.",
  info_proposal_title: "Proposal from the agent for this scene",
  info_proposal_same: "already set",
  info_proposal_accept: "Accept selected",
  ai_err_fields_invalid: "These fields are not (or no longer) in the proposal.",
  ai_err_nothing_changed: "The proposal changes nothing.",
  entity_proposal_new: "Proposal from the agent: new entry ({{group}})",
  entity_proposal_change: "Proposal from the agent: change to this profile",
  entity_proposal_apply: "Apply change",
  entity_proposal_create: "Create",
  entity_proposal_badge: "Proposal",
  ai_err_entity_not_found: "This profile no longer exists – please discard the proposal.",
  ai_err_entity_exists: "A profile with this name already exists.",
  ai_err_entity_invalid: "The profile proposal is invalid.",
}
