import { useEffect, useState } from "react"
import { Archive, FolderTree, Landmark, Pencil, Plus, RotateCcw } from "lucide-react"
import { AdminConfirmDialog } from "@/features/cockpit/admin/ui/AdminConfirmDialog"
import { errorMessage, haushaltsbuchApi, isConflict } from "./api"
import { AccountDialog, CategoryDialog } from "./AssetDialogs"
import { formatMinorUnits } from "./money"
import type { Account, Category, Household } from "./types"
import { Button, EmptyState, ErrorState, LoadingState, panel } from "./ui"

export function AccountsView({ household, onChanged }: { household: Household; onChanged: () => void }) {
  const [accounts, setAccounts] = useState<Account[]>(); const [categories, setCategories] = useState<Category[]>()
  const [showArchived, setShowArchived] = useState(false); const [error, setError] = useState<unknown>(); const [dialog, setDialog] = useState<"account" | "category" | null>(null)
  const [editAccount, setEditAccount] = useState<Account>(); const [editCategory, setEditCategory] = useState<Category>(); const [confirm, setConfirm] = useState<Account | Category>()
  const load = () => { setError(undefined); Promise.all([haushaltsbuchApi.accounts(showArchived), haushaltsbuchApi.categories(showArchived)]).then(([a, c]) => { setAccounts(a); setCategories(c) }).catch(setError) }
  useEffect(load, [showArchived])
  async function toggleArchived() { if (!confirm) return; try { if ("balance_base" in confirm) await haushaltsbuchApi.updateAccount(confirm.id, { name: confirm.name, type: confirm.type, owner_member_id: confirm.owner_member_id, bank_identifier: confirm.bank_identifier, archived: !confirm.archived, revision: confirm.revision }); else await haushaltsbuchApi.updateCategory(confirm.id, { name: confirm.name, kind: confirm.kind, parent_id: confirm.parent_id, icon: confirm.icon, color: confirm.color, sort_order: confirm.sort_order, archived: !confirm.archived, revision: confirm.revision }); setConfirm(undefined); load(); onChanged() } catch (cause) { setError(cause); setConfirm(undefined) } }
  if (error && !accounts) return <ErrorState error={errorMessage(error)} conflict={isConflict(error)} onRetry={load} />
  if (!accounts || !categories) return <LoadingState />
  const saved = () => { setDialog(null); setEditAccount(undefined); setEditCategory(undefined); load(); onChanged() }
  return <div className="space-y-5">{error !== undefined && <ErrorState error={errorMessage(error)} conflict={isConflict(error)} onRetry={load} />}
    <div className="flex flex-wrap items-center gap-2"><label className="mr-auto flex items-center gap-2 text-xs text-[#8d9ab0]"><input type="checkbox" checked={showArchived} onChange={(e) => setShowArchived(e.target.checked)} />Archivierte anzeigen</label><Button onClick={() => { setEditCategory(undefined); setDialog("category") }}><Plus size={13} className="mr-1 inline" />Kategorie</Button><Button tone="primary" onClick={() => { setEditAccount(undefined); setDialog("account") }}><Plus size={13} className="mr-1 inline" />Konto</Button></div>
    <section><h2 className="mb-3 flex items-center gap-2 font-bold text-[#e8eef8]"><Landmark size={17} className="text-cyan-300" />Konten</h2>{accounts.length ? <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{accounts.map((account) => <article key={account.id} className={`${panel} p-4 ${account.archived ? "opacity-60" : ""}`}><div className="flex items-start gap-2"><div className="min-w-0 flex-1"><h3 className="truncate font-bold text-[#e8eef8]">{account.name}</h3><p className="text-xs text-[#718097]">{account.type} · {account.currency}{account.archived ? " · Archiviert" : ""}</p></div><Button className="px-2" aria-label="Bearbeiten" onClick={() => { setEditAccount(account); setDialog("account") }}><Pencil size={13} /></Button><Button className="px-2" aria-label={account.archived ? "Reaktivieren" : "Archivieren"} onClick={() => setConfirm(account)}>{account.archived ? <RotateCcw size={13} /> : <Archive size={13} />}</Button></div><p className="mt-4 text-lg font-black tabular-nums text-[#d4deeb]">{formatMinorUnits(account.balance_base, household.base_currency)}</p>{account.currency !== household.base_currency && <p className="mt-1 text-xs text-amber-200">Saldo in Basiswährung</p>}</article>)}</div> : <EmptyState title="Keine Konten" text="Lege ein Girokonto, Bargeldkonto oder anderes Finanzkonto an." />}</section>
    <section><h2 className="mb-3 flex items-center gap-2 font-bold text-[#e8eef8]"><FolderTree size={17} className="text-cyan-300" />Kategorien</h2>{categories.length ? <div className={`${panel} divide-y divide-[#263247]`}>{categories.map((category) => <div key={category.id} className={`flex items-center gap-3 px-4 py-3 ${category.archived ? "opacity-60" : ""}`}><span className="h-3 w-3 rounded-full border border-white/20" style={{ backgroundColor: category.color ?? "#546E7A" }} /><span className="min-w-0 flex-1 text-sm text-[#d4deeb]">{category.parent_id ? "↳ " : ""}{category.name}<small className="ml-2 text-[#718097]">{category.kind === "expense" ? "Ausgabe" : "Einnahme"}{category.archived ? " · Archiviert" : ""}</small></span><Button className="px-2" onClick={() => { setEditCategory(category); setDialog("category") }}><Pencil size={13} /></Button><Button className="px-2" onClick={() => setConfirm(category)}>{category.archived ? <RotateCcw size={13} /> : <Archive size={13} />}</Button></div>)}</div> : <EmptyState title="Keine Kategorien" text="Lege Kategorien für Einnahmen und Ausgaben an." />}</section>
    {dialog === "account" && <AccountDialog household={household} members={household.members} account={editAccount} onClose={() => setDialog(null)} onSaved={saved} />}{dialog === "category" && <CategoryDialog categories={categories} category={editCategory} onClose={() => setDialog(null)} onSaved={saved} />}
    {confirm && <AdminConfirmDialog title={confirm.archived ? "Eintrag reaktivieren?" : "Eintrag archivieren?"} confirmLabel={confirm.archived ? "Reaktivieren" : "Archivieren"} cancelLabel="Abbrechen" confirmTone={confirm.archived ? "primary" : "danger"} onClose={() => setConfirm(undefined)} onConfirm={toggleArchived}>„{confirm.name}“ bleibt für historische Buchungen erhalten.</AdminConfirmDialog>}
  </div>
}
