import { useEffect, useState, type FormEvent } from "react"
import { CalendarClock, Pause, Pencil, Play, Plus, TriangleAlert } from "lucide-react"
import { AdminDialog } from "@/features/cockpit/admin/ui/AdminDialog"
import { AdminConfirmDialog } from "@/features/cockpit/admin/ui/AdminConfirmDialog"
import { errorMessage, haushaltsbuchApi, isConflict } from "./api"
import { formatMinorUnits, minorToInput, parseMinorUnits } from "./money"
import type { Account, Category, Household, RecurringFrequency, RecurringRule } from "./types"
import { Button, EmptyState, ErrorState, Field, Input, LoadingState, Select, Textarea, panel } from "./ui"

const today = new Date().toISOString().slice(0, 10)
const frequencyLabels: Record<RecurringFrequency, string> = { daily: "Täglich", weekly: "Wöchentlich", monthly: "Monatlich", yearly: "Jährlich" }
export function RecurringView({ household, onChanged }: { household: Household; onChanged: () => void }) {
  const [rules, setRules] = useState<RecurringRule[]>(); const [accounts, setAccounts] = useState<Account[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [error, setError] = useState<unknown>(); const [edit, setEdit] = useState<RecurringRule | null | undefined>(); const [toggle, setToggle] = useState<RecurringRule>()
  const load = () => { setError(undefined); Promise.all([haushaltsbuchApi.recurring(true), haushaltsbuchApi.accounts(), haushaltsbuchApi.categories()]).then(([r, a, c]) => { setRules(r); setAccounts(a); setCategories(c) }).catch(setError) }; useEffect(load, [])
  async function toggleStatus() { if (!toggle) return; try { const { id, revision, overdue: _, ...body } = toggle; await haushaltsbuchApi.updateRecurring(id, { ...body, status: toggle.status === "inactive" ? "confirmed" : "inactive", revision }); setToggle(undefined); load(); onChanged() } catch (cause) { setError(cause); setToggle(undefined) } }
  if (!rules) return error ? <ErrorState error={errorMessage(error)} conflict={isConflict(error)} onRetry={load} /> : <LoadingState />
  return <div className="space-y-4">{error !== undefined && <ErrorState error={errorMessage(error)} conflict={isConflict(error)} onRetry={load} />}<div className="flex justify-end"><Button tone="primary" onClick={() => setEdit(null)}><Plus size={13} className="mr-1 inline" />Serie anlegen</Button></div>{rules.length ? <div className="grid gap-3 lg:grid-cols-2">{rules.map((rule) => <article key={rule.id} className={`${panel} p-4 ${rule.status === "inactive" ? "opacity-60" : ""}`}><div className="flex items-start gap-3"><CalendarClock size={18} className="mt-0.5 text-cyan-300" /><div className="min-w-0 flex-1"><h3 className="truncate font-bold text-[#e8eef8]">{rule.counterparty || "Wiederkehrende Zahlung"}</h3><p className="text-xs text-[#718097]">{frequencyLabels[rule.frequency]}{rule.interval_count > 1 ? ` · alle ${rule.interval_count} Intervalle` : ""} · {rule.status === "confirmed" ? "Bestätigt" : rule.status === "inactive" ? "Pausiert" : "Entwurf"}</p></div><Button className="px-2" onClick={() => setEdit(rule)}><Pencil size={13} /></Button><Button className="px-2" onClick={() => setToggle(rule)}>{rule.status === "inactive" ? <Play size={13} /> : <Pause size={13} />}</Button></div><div className="mt-4 flex items-end justify-between"><div><p className="text-xs text-[#8d9ab0]">Nächste Fälligkeit</p><p className={rule.overdue ? "font-bold text-amber-200" : "font-bold text-[#d4deeb]"}>{new Date(`${rule.next_due_date}T12:00:00`).toLocaleDateString()}{rule.overdue ? " · Überfällig" : ""}</p></div><strong className={rule.kind === "expense" ? "text-rose-200" : "text-emerald-200"}>{rule.kind === "expense" ? "−" : "+"}{formatMinorUnits(rule.amount, household.base_currency)}</strong></div>{rule.overdue && <p className="mt-3 flex gap-2 rounded bg-amber-500/10 p-2 text-xs text-amber-100"><TriangleAlert size={14} />Überfällige Serien werden niemals automatisch gebucht.</p>}</article>)}</div> : <EmptyState title="Keine wiederkehrenden Zahlungen" text="Erfasse Miete, Gehalt, Abos oder andere regelmäßige Vorgänge." />}{edit !== undefined && <RecurringDialog household={household} accounts={accounts} categories={categories} rule={edit ?? undefined} onClose={() => setEdit(undefined)} onSaved={() => { setEdit(undefined); load(); onChanged() }} />}{toggle && <AdminConfirmDialog title={toggle.status === "inactive" ? "Serie fortsetzen?" : "Serie pausieren?"} confirmLabel={toggle.status === "inactive" ? "Fortsetzen" : "Pausieren"} cancelLabel="Abbrechen" confirmTone={toggle.status === "inactive" ? "primary" : "danger"} onClose={() => setToggle(undefined)} onConfirm={toggleStatus}>Die Prognose wird unmittelbar neu berechnet. Es wird keine Finanzbuchung erzeugt.</AdminConfirmDialog>}</div>
}
function RecurringDialog({ household, accounts, categories, rule, onClose, onSaved }: { household: Household; accounts: Account[]; categories: Category[]; rule?: RecurringRule; onClose: () => void; onSaved: () => void }) {
  const [kind, setKind] = useState<"income" | "expense">(rule?.kind ?? "expense"); const [account, setAccount] = useState(String(rule?.account_id ?? accounts[0]?.id ?? "")); const [category, setCategory] = useState(String(rule?.category_id ?? "")); const [frequency, setFrequency] = useState<RecurringFrequency>(rule?.frequency ?? "monthly"); const [interval, setInterval] = useState(rule?.interval_count ?? 1); const [due, setDue] = useState(rule?.next_due_date ?? today); const [end, setEnd] = useState(rule?.end_date ?? ""); const [amount, setAmount] = useState(rule ? minorToInput(rule.amount, household.base_currency) : ""); const [tolerance, setTolerance] = useState(rule ? minorToInput(rule.tolerance, household.base_currency) : "0"); const [counterparty, setCounterparty] = useState(rule?.counterparty ?? ""); const [notice, setNotice] = useState(rule?.cancellation_notice_days == null ? "" : String(rule.cancellation_notice_days)); const [note, setNote] = useState(rule?.note ?? ""); const [error, setError] = useState<unknown>(); const [busy, setBusy] = useState(false)
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(undefined); try { const body = { kind, account_id: Number(account), category_id: Number(category), frequency, interval_count: interval, next_due_date: due, end_date: end || null, anchor_day: frequency === "monthly" ? Number(due.slice(8, 10)) : null, amount: parseMinorUnits(amount, household.base_currency), tolerance: parseMinorUnits(tolerance, household.base_currency), counterparty: counterparty.trim() || null, cancellation_notice_days: notice === "" ? null : Number(notice), note: note.trim() || null, status: rule?.status ?? "confirmed" as const, confidence: rule?.confidence ?? "1" }; if (rule) await haushaltsbuchApi.updateRecurring(rule.id, { ...body, revision: rule.revision }); else await haushaltsbuchApi.createRecurring(body); onSaved() } catch (cause) { setError(cause) } finally { setBusy(false) } }
  const matching = categories.filter((item) => item.kind === kind && !item.archived)
  return <AdminDialog title={rule ? "Serie bearbeiten" : "Serie anlegen"} eyebrow="Haushaltsbuch · Wiederkehrend" icon={<CalendarClock size={16} />} maxWidthClass="max-w-2xl" onClose={busy ? undefined : onClose} footer={<><Button onClick={onClose}>Abbrechen</Button><Button tone="primary" type="submit" form="recurring-form" disabled={busy}>Speichern</Button></>}><form id="recurring-form" onSubmit={submit} className="grid gap-4">{error !== undefined && <ErrorState error={errorMessage(error)} conflict={isConflict(error)} />}<div className="grid gap-4 sm:grid-cols-2"><Field label="Art"><Select value={kind} onChange={(e) => { setKind(e.target.value as "income" | "expense"); setCategory("") }}><option value="expense">Ausgabe</option><option value="income">Einnahme</option></Select></Field><Field label="Konto"><Select required value={account} onChange={(e) => setAccount(e.target.value)}>{accounts.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field></div><Field label="Kategorie"><Select required value={category} onChange={(e) => setCategory(e.target.value)}><option value="">Auswählen …</option>{matching.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field><div className="grid gap-4 sm:grid-cols-3"><Field label="Frequenz"><Select value={frequency} onChange={(e) => setFrequency(e.target.value as RecurringFrequency)}>{Object.entries(frequencyLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</Select></Field><Field label="Intervall"><Input required type="number" min={1} max={365} value={interval} onChange={(e) => setInterval(Number(e.target.value))} /></Field><Field label={`Betrag (${household.base_currency})`}><Input required inputMode="decimal" value={amount} onChange={(e) => setAmount(e.target.value)} /></Field></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Nächste Fälligkeit"><Input required type="date" value={due} onChange={(e) => setDue(e.target.value)} /></Field><Field label="Enddatum (optional)"><Input type="date" min={due} value={end} onChange={(e) => setEnd(e.target.value)} /></Field></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Vertragspartner"><Input maxLength={240} value={counterparty} onChange={(e) => setCounterparty(e.target.value)} /></Field><Field label={`Toleranz (${household.base_currency})`}><Input inputMode="decimal" value={tolerance} onChange={(e) => setTolerance(e.target.value)} /></Field></div><Field label="Kündigungsfrist (Tage)"><Input type="number" min={0} value={notice} onChange={(e) => setNotice(e.target.value)} /></Field><Field label="Notiz"><Textarea rows={2} value={note} onChange={(e) => setNote(e.target.value)} /></Field></form></AdminDialog>
}
