import { useEffect, useState, type FormEvent } from "react"
import { Ban, Filter, Plus, Receipt } from "lucide-react"
import { AdminConfirmDialog } from "@/features/cockpit/admin/ui/AdminConfirmDialog"
import { errorMessage, haushaltsbuchApi, isConflict } from "./api"
import { formatMinorUnits } from "./money"
import { TransactionDialog } from "./TransactionDialog"
import type { Account, Category, Household, Transaction, TransactionFilters } from "./types"
import { Button, EmptyState, ErrorState, Input, LoadingState, Select, panel } from "./ui"

export function TransactionsView({ household, onChanged }: { household: Household; onChanged: () => void }) {
  const [transactions, setTransactions] = useState<Transaction[]>(); const [accounts, setAccounts] = useState<Account[]>([]); const [categories, setCategories] = useState<Category[]>([])
  const [filters, setFilters] = useState<TransactionFilters>({ limit: 100 }); const [draft, setDraft] = useState({ date_from: "", date_to: "", account_id: "", category_id: "", query: "" }); const [error, setError] = useState<unknown>(); const [open, setOpen] = useState(false); const [reverse, setReverse] = useState<Transaction>(); const [busy, setBusy] = useState(false)
  const load = () => { setError(undefined); Promise.all([haushaltsbuchApi.transactions(filters), haushaltsbuchApi.accounts(), haushaltsbuchApi.categories()]).then(([tx, ac, ca]) => { setTransactions(tx); setAccounts(ac); setCategories(ca) }).catch(setError) }
  useEffect(load, [filters])
  function apply(event: FormEvent) { event.preventDefault(); setFilters({ date_from: draft.date_from || undefined, date_to: draft.date_to || undefined, account_id: draft.account_id ? Number(draft.account_id) : undefined, category_id: draft.category_id ? Number(draft.category_id) : undefined, query: draft.query.trim() || undefined, limit: 100 }) }
  async function confirmReverse() { if (!reverse) return; setBusy(true); try { await haushaltsbuchApi.reverseTransaction(reverse.id, reverse.revision); setReverse(undefined); load(); onChanged() } catch (cause) { setError(cause); setReverse(undefined) } finally { setBusy(false) } }
  if (!transactions) return error ? <ErrorState error={errorMessage(error)} conflict={isConflict(error)} onRetry={load} /> : <LoadingState />
  const amount = (tx: Transaction) => { const posting = tx.postings?.find((item) => item.account_id != null); return posting ? formatMinorUnits(posting.base_amount, household.base_currency) : "Details nach Öffnen" }
  return <div className="space-y-4">{error !== undefined && <ErrorState error={errorMessage(error)} conflict={isConflict(error)} onRetry={load} />}<div className="flex justify-end"><Button tone="primary" onClick={() => setOpen(true)} disabled={!accounts.length || !categories.length}><Plus size={13} className="mr-1 inline" />Buchung erfassen</Button></div>
    <form onSubmit={apply} className={`${panel} grid gap-2 p-3 md:grid-cols-[9rem_9rem_1fr_1fr_1.4fr_auto]`}><Input aria-label="Von" type="date" value={draft.date_from} onChange={(e) => setDraft({ ...draft, date_from: e.target.value })} /><Input aria-label="Bis" type="date" value={draft.date_to} onChange={(e) => setDraft({ ...draft, date_to: e.target.value })} /><Select aria-label="Konto" value={draft.account_id} onChange={(e) => setDraft({ ...draft, account_id: e.target.value })}><option value="">Alle Konten</option>{accounts.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Select aria-label="Kategorie" value={draft.category_id} onChange={(e) => setDraft({ ...draft, category_id: e.target.value })}><option value="">Alle Kategorien</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select><Input aria-label="Suche" value={draft.query} onChange={(e) => setDraft({ ...draft, query: e.target.value })} placeholder="Empfänger, Zweck, Notiz" /><Button type="submit"><Filter size={13} className="mr-1 inline" />Filtern</Button></form>
    {transactions.length ? <div className={`${panel} overflow-x-auto`}><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b border-[#2a364b] text-xs text-[#718097]"><tr><th className="px-4 py-3">Datum</th><th className="px-4 py-3">Empfänger / Zweck</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Betrag</th><th className="w-20 px-4 py-3" /></tr></thead><tbody className="divide-y divide-[#263247]">{transactions.map((tx) => <tr key={tx.id} className={tx.status === "reversed" ? "opacity-60" : ""}><td className="px-4 py-3 text-[#8d9ab0]">{new Date(`${tx.booking_date}T12:00:00`).toLocaleDateString()}</td><td className="max-w-sm px-4 py-3"><strong className="block truncate text-[#d4deeb]">{tx.counterparty || `Buchung #${tx.id}`}</strong><span className="block truncate text-xs text-[#718097]">{tx.purpose || "Kein Verwendungszweck"}</span></td><td className="px-4 py-3 text-xs uppercase text-[#8d9ab0]">{tx.status === "reversed" ? "Storniert" : "Gebucht"}</td><td className="px-4 py-3 text-right text-xs tabular-nums text-[#b5c1d2]">{amount(tx)}</td><td className="px-4 py-3">{tx.status === "posted" && <Button className="px-2" tone="danger" aria-label="Stornieren" onClick={() => setReverse(tx)}><Ban size={13} /></Button>}</td></tr>)}</tbody></table></div> : <EmptyState title="Keine Buchungen gefunden" text="Passe die Filter an oder erfasse die erste Buchung." action={<Button tone="primary" onClick={() => setOpen(true)}><Receipt size={13} className="mr-1 inline" />Buchung erfassen</Button>} />}
    {open && <TransactionDialog household={household} accounts={accounts} categories={categories} onClose={() => setOpen(false)} onSaved={() => { setOpen(false); load(); onChanged() }} />}{reverse && <AdminConfirmDialog title="Buchung stornieren?" confirmLabel="Storno erzeugen" cancelLabel="Abbrechen" onClose={() => setReverse(undefined)} onConfirm={confirmReverse} busy={busy}>Die Buchung wird nicht gelöscht. Es entsteht ein auditierbarer Gegenbuchungsvorgang.</AdminConfirmDialog>}
  </div>
}
