from __future__ import annotations

FORBIDDEN_SINGLE = {
    "CAM", "CAMRIP", "HDCAM", "TS", "HDTS", "TELESYNC", "TC", "TELECINE",
    "SCR", "SCREENER", "SCREENERS", "DVDSCR", "WEBSCREENER", "WORKPRINT", "R5",
}
FORBIDDEN_PAIRS = {
    ("CAM", "RIP"), ("HD", "CAM"), ("HD", "TS"), ("TELE", "SYNC"),
    ("TELE", "CINE"), ("DVD", "SCR"), ("WEB", "SCREENER"), ("WORK", "PRINT"),
}
GERMAN_TOKENS = {"GERMAN", "DEUTSCH", "DE", "GER"}
SAMPLE_TOKENS = {"SAMPLE", "SAMPLES", "HOERPROBE", "AUSZUG", "EXCERPT", "PREVIEW"}
INCOMPLETE_TOKENS = {"INCOMPLETE", "UNVOLLSTAENDIG", "PARTIAL"}
AUDIOPLAY_TOKENS = {"HOERSPIEL", "RADIOPLAY", "AUDIODRAMA"}
BOOK_ALLOWED = {"EPUB": "epub", "PDF": "pdf"}
AUDIO_ALLOWED = {"MP3": "mp3", "M4B": "m4b"}
MUSIC_ALLOWED = {"FLAC": "flac", "MP3": "mp3"}
KNOWN_DISALLOWED_FORMATS = {"MOBI", "AZW3", "TXT", "AAC", "OGG", "WAV", "ALAC"}
