import { TicketsPage } from "./TicketsPage"

export const routes = [{ path: "/tickets", element: <TicketsPage /> }]

export const nav = [
  {
    path: "/tickets",
    icon: "Ticket",
    labelKey: "tickets",
    group: "working",
    roles: [] as ("admin" | "user")[],
  },
]

export const i18n = {
  de: {
    tickets: {
      title: "Tickets",
      subtitle: "Interne Vorgänge und Teamarbeit",
      inbox: "Posteingang",
      newTicket: "Neues Ticket",
      search: "Tickets durchsuchen…",
      allStatuses: "Alle Status",
      allPriorities: "Alle Prioritäten",
      loading: "Tickets werden geladen…",
      empty: "Keine Tickets gefunden.",
      selectTicket: "Wähle ein Ticket aus oder lege ein neues an.",
      status: { open: "Offen", triaged: "Triage", in_progress: "In Arbeit", waiting: "Wartet", resolved: "Gelöst", closed: "Geschlossen", cancelled: "Abgebrochen" },
      priority: { low: "Niedrig", normal: "Normal", high: "Hoch", urgent: "Dringend" },
      statusLabel: "Status",
      priorityLabel: "Priorität",
      team: "Team",
      assignedTo: "Zugewiesen an",
      unassigned: "Nicht zugewiesen",
      conversation: "Interner Verlauf",
      comment: "Kommentieren",
      commentPlaceholder: "Internen Kommentar schreiben…",
      noComments: "Noch keine Kommentare.",
      attachments: "Anhänge",
      upload: "Anhang hinzufügen",
      noAttachments: "Keine Anhänge.",
      links: "Verknüpfungen",
      project: "Projekt",
      task: "Task",
      session: "Session",
      noDescription: "Keine Beschreibung.",
      titleField: "Titel",
      descriptionField: "Beschreibung",
      categoryField: "Kategorie",
      cancel: "Abbrechen",
      create: "Erstellen",
      saving: "Speichert…",
      internalOnly: "Nur für authentifizierte HydraHive-Benutzer sichtbar.",
      saveError: "Änderung konnte nicht gespeichert werden.",
      uploadError: "Anhang konnte nicht hochgeladen werden.",
      loadError: "Tickets konnten nicht geladen werden.",
      teams: "Teams",
      teamName: "Teamname",
      createTeam: "Team anlegen",
      teamError: "Team konnte nicht angelegt werden (Admin-Rechte erforderlich).",
      members: "Mitglieder",
      userId: "User-ID",
      addMember: "Mitglied hinzufügen",
      noTeams: "Noch keine Teams.",
      notifications: "Benachrichtigungen",
      noNotifications: "Keine neuen Benachrichtigungen.",
      notification: {},
    },
  },
  en: {
    tickets: {
      title: "Tickets",
      subtitle: "Internal issues and team work",
      inbox: "Inbox",
      newTicket: "New ticket",
      search: "Search tickets…",
      allStatuses: "All statuses",
      allPriorities: "All priorities",
      loading: "Loading tickets…",
      empty: "No tickets found.",
      selectTicket: "Select a ticket or create a new one.",
      status: { open: "Open", triaged: "Triaged", in_progress: "In progress", waiting: "Waiting", resolved: "Resolved", closed: "Closed", cancelled: "Cancelled" },
      priority: { low: "Low", normal: "Normal", high: "High", urgent: "Urgent" },
      statusLabel: "Status",
      priorityLabel: "Priority",
      team: "Team",
      assignedTo: "Assigned to",
      unassigned: "Unassigned",
      conversation: "Internal conversation",
      comment: "Comment",
      commentPlaceholder: "Write an internal comment…",
      noComments: "No comments yet.",
      attachments: "Attachments",
      upload: "Add attachment",
      noAttachments: "No attachments.",
      links: "Links",
      project: "Project",
      task: "Task",
      session: "Session",
      noDescription: "No description.",
      titleField: "Title",
      descriptionField: "Description",
      categoryField: "Category",
      cancel: "Cancel",
      create: "Create",
      saving: "Saving…",
      internalOnly: "Visible to authenticated HydraHive users only.",
      saveError: "The change could not be saved.",
      uploadError: "The attachment could not be uploaded.",
      loadError: "Tickets could not be loaded.",
      teams: "Teams",
      teamName: "Team name",
      createTeam: "Create team",
      teamError: "Team could not be created (admin permission required).",
      members: "members",
      userId: "User ID",
      addMember: "Add member",
      noTeams: "No teams yet.",
      notifications: "Notifications",
      noNotifications: "No new notifications.",
      notification: {},
    },
  },
}
