import { TicketsPage } from "./TicketsPage"

export const routes = [{ path: "/tickets", element: <TicketsPage /> }]

export const nav = [
  {
    path: "/tickets",
    icon: "Ticket",
    labelKey: "tickets",
    group: "working",
    topnav: true,
    cockpit: true,
    roles: [] as ("admin" | "user")[],
  },
]

export const i18n = {
  de: {
    tickets: {
      title: "Tickets",
      subtitle: "Interne Vorgänge und Teamarbeit",
      internalBadge: "Intern",
      inbox: "Posteingang",
      ticketsCount: "Tickets",
      newTicket: "Neues Ticket",
      backToInbox: "Zurück zum Posteingang",
      search: "Tickets durchsuchen…",
      allStatuses: "Alle Status",
      allPriorities: "Alle Prioritäten",
      loading: "Tickets werden geladen…",
      empty: "Keine Tickets gefunden.",
      emptyHint: "Passe deine Filter an oder erstelle einen neuen Vorgang.",
      selectTicketTitle: "Wähle einen Vorgang aus",
      selectTicket: "Öffne ein Ticket aus dem Posteingang, um den Verlauf, Zuständigkeiten und Anhänge zu sehen.",
      lastUpdated: "Zuletzt aktualisiert",
      status: { open: "Offen", triaged: "Triage", in_progress: "In Arbeit", waiting: "Wartet", resolved: "Gelöst", closed: "Geschlossen", cancelled: "Abgebrochen" },
      priority: { low: "Niedrig", normal: "Normal", high: "Hoch", urgent: "Dringend" },
      statusLabel: "Status",
      priorityLabel: "Priorität",
      requester: "Anfragende Person",
      team: "Team",
      assignedTo: "Zugewiesen an",
      unassigned: "Nicht zugewiesen",
      created: "Erstellt",
      categoryField: "Kategorie",
      ticketControls: "Ticket verwalten",
      conversation: "Interner Verlauf",
      commentsCount: "Kommentare",
      agent: "Agent",
      comment: "Kommentieren",
      commentPlaceholder: "Internen Kommentar schreiben…",
      noComments: "Noch keine Kommentare.",
      attachments: "Anhänge",
      upload: "Anhang hinzufügen",
      noAttachments: "Keine Anhänge.",
      links: "Verknüpfungen",
      githubIntegration: "GitHub-Verknüpfung",
      githubConnectionId: "Verbindungs-ID",
      githubOwner: "Owner",
      githubRepository: "Repository",
      githubLink: "Issue verknüpfen",
      githubUnlink: "Verknüpfung lösen",
      githubLinkError: "GitHub-Verknüpfung konnte nicht gespeichert werden.",
      githubSettings: "GitHub-Projektintegration",
      githubProjectId: "HydraHive-Projekt-ID",
      githubProjectsLoading: "Projekte werden geladen …",
      githubProjectsError: "HydraHive-Projekte konnten nicht geladen werden.",
      githubProjectsEmpty: "Keine zugänglichen Projekte vorhanden.",
      githubChooseCredential: "GitHub-Credential auswählen",
      githubChooseOwner: "GitHub-Owner auswählen",
      githubChooseRepository: "GitHub-Repository auswählen",
      githubReposLoading: "Projekt-Repositories werden geladen …",
      githubReposError: "Projekt-Repositories konnten nicht geladen werden.",
      githubReposEmpty: "Keine GitHub-Repositories mit Projekt-Token gefunden.",
      githubDiscoveryLoading: "GitHub-Daten werden geladen …",
      githubDiscoveryError: "GitHub-Daten konnten nicht geladen werden.",
      githubNoCredential: "Kein passendes GitHub-Bearer-Credential vorhanden. Unter Credentials anlegen.",
      githubChooseConnection: "GitHub-Verbindung auswählen",
      githubNoConnection: "Keine GitHub-Verbindung für dieses Projekt",
      githubCredential: "Credential-Name",
      githubAdd: "Verbindung hinzufügen",
      githubDisable: "Verbindung deaktivieren",
      githubSaved: "Verbindung gespeichert. Die Issues findest du oben über „GitHub-Workbench“.",
      githubAlreadyConnected: "Dieses Repository ist bereits verbunden. Öffne oben die GitHub-Workbench, um die Issues zu sehen.",
      githubConnected: "bereits verbunden",
      githubAlreadyConnectedShort: "Bereits verbunden",
      githubModeSaved: "GitHub-Schreibmodus gespeichert.",
      githubModeReadOnly: "Nur lesen",
      githubModePush: "Push",
      githubModeBidirectional: "Bidirektional",
      githubSettingsError: "GitHub-Verbindung konnte nicht gespeichert werden.",
      githubWorkbench: "GitHub-Workbench",
      githubWorkbenchChooseProject: "Wähle ein HydraHive-Projekt, um die GitHub-Tickets zu öffnen.",
      githubWorkbenchNoConnection: "Für dieses Projekt ist noch keine GitHub-Verbindung eingerichtet.",
      githubWorkbenchError: "Die GitHub-Workbench konnte die Daten nicht laden.",
      githubRemoteIssues: "GitHub-Issues",
      githubRemoteIssuesHint: "Offene Issues des verbundenen Repositories.",
      githubLocalTickets: "HydraHive-Tickets",
      githubLocalTicketsHint: "Importierte Issues mit dem normalen HydraHive-Ticketworkflow.",
      githubNoRemoteIssues: "Keine offenen GitHub-Issues gefunden.",
      githubNoImportedTickets: "Noch keine Issues als HydraHive-Tickets importiert.",
      githubImportedTicket: "Als HydraHive-Ticket #{number} importiert",
      githubNotImported: "Noch nicht als HydraHive-Ticket importiert",
      githubOpenTicket: "Ticket öffnen",
      githubImportTicket: "Als Ticket importieren",
      githubOpenExternal: "Auf GitHub öffnen",
      githubSync: "Jetzt synchronisieren",
      githubStateOpen: "Offen",
      githubStateClosed: "Geschlossen",
      githubStateAll: "Alle",
      githubIssuesTab: "Issues",
      githubBoardTab: "Project-Board",
      githubBoardTitle: "GitHub-Project-Board",
      githubBoardHint: "Project-Items und Statusfelder des ausgewählten GitHub-Projects.",
      githubBoardWriteEnabled: "Schreibzugriff aktiv",
      githubBoardReadOnly: "Nur lesen",
      githubBoardEmpty: "Keine Project-Items gefunden.",
      githubBoardNoStatus: "Kein Status",
      githubAddToProject: "Ins Project",
      githubSyncDone: "{count} Issues synchronisiert, {created} neue Tickets angelegt.",
      githubPush: "Zu GitHub senden",
      githubPushError: "Die Änderung konnte nicht zu GitHub synchronisiert werden.",
      githubLoading: "GitHub-Daten werden geladen …",
      githubItemsTitle: "GitHub-Projektaufgaben",
      githubIssuesLoading: "Offene dir zugewiesene GitHub-Issues werden geladen …",
      githubIssuesError: "Die zugewiesenen GitHub-Issues konnten nicht geladen werden.",
      githubIssuesEmpty: "Keine offenen Issues gefunden, die deinem GitHub-Account zugewiesen sind.",
      githubIssueOpen: "offen",
      githubChooseProject: "GitHub-Project auswählen",
      githubItemsLoading: "GitHub-Projects und Aufgaben werden geladen …",
      githubItemsError: "GitHub-Projects oder Aufgaben konnten nicht geladen werden.",
      githubItemsNoConnection: "Für dieses Projekt ist noch keine GitHub-Verbindung eingerichtet.",
      githubItemsNoProjects: "Keine GitHub-Projects gefunden oder Berechtigung fehlt.",
      githubItemsEmpty: "Dieses GitHub-Project enthält keine sichtbaren Aufgaben.",
      githubItemsUntitled: "Aufgabe ohne Titel",
      githubOpenItem: "Aufgabe auf GitHub öffnen",
      project: "Projekt",
      task: "Task",
      session: "Session",
      noDescription: "Keine Beschreibung.",
      titleField: "Titel",
      titlePlaceholder: "Kurze Zusammenfassung des Vorgangs",
      descriptionField: "Beschreibung",
      descriptionPlaceholder: "Beschreibe das Problem, den Kontext oder die gewünschte Unterstützung…",
      categoryPlaceholder: "z. B. Infrastruktur",
      cancel: "Abbrechen",
      create: "Ticket erstellen",
      saving: "Speichert…",
      internalOnly: "Nur für authentifizierte HydraHive-Benutzer sichtbar.",
      saveError: "Änderung konnte nicht gespeichert werden.",
      uploadError: "Anhang konnte nicht hochgeladen werden.",
      loadError: "Tickets konnten nicht geladen werden.",
      teams: "Teams",
      teamName: "Teamname",
      teamDescription: "Kurzbeschreibung (optional)",
      createTeam: "Team anlegen",
      teamError: "Team konnte nicht angelegt werden (Admin-Rechte erforderlich).",
      removeMember: "Mitglied entfernen",
      userId: "User-ID",
      addMember: "Mitglied hinzufügen",
      noTeams: "Noch keine Teams.",
      notifications: "Benachrichtigungen",
      unread: "ungelesen",
      open: "Öffnen",
      noNotifications: "Keine neuen Benachrichtigungen.",
      dueDate: "Fälligkeit (manuell)",
      manualDueDate: "Manuelle Fälligkeit",
      slaDueDate: "SLA-Fälligkeit",
      resetDueDate: "SLA-Berechnung wiederherstellen",
      selected: "ausgewählt",
      bulkPriority: "Priorität ändern",
      savedViews: "Gespeicherte Ansichten",
      chooseView: "Ansicht auswählen",
      viewName: "Name der Ansicht",
      saveView: "Ansicht speichern",
      deleteView: "Ansicht löschen",
      slaProfiles: "SLA-Profil",
      slaProfilesHint: "Fristen in Stunden. Änderungen gelten für neue oder neu berechnete Tickets.",
      resolution: "Lösung",
      save: "Speichern",
      dashboard: { open: "Offen", overdue: "Überfällig", dueSoon: "Bald fällig", mine: "Meine Tickets", unassigned: "Ohne Zuweisung" },
      notification: {},
    },
  },
  en: {
    tickets: {
      title: "Tickets",
      subtitle: "Internal issues and team work",
      internalBadge: "Internal",
      inbox: "Inbox",
      ticketsCount: "tickets",
      newTicket: "New ticket",
      backToInbox: "Back to inbox",
      search: "Search tickets…",
      allStatuses: "All statuses",
      allPriorities: "All priorities",
      loading: "Loading tickets…",
      empty: "No tickets found.",
      emptyHint: "Adjust your filters or create a new issue.",
      selectTicketTitle: "Select an issue",
      selectTicket: "Open a ticket from the inbox to see its conversation, ownership and attachments.",
      lastUpdated: "Last updated",
      status: { open: "Open", triaged: "Triaged", in_progress: "In progress", waiting: "Waiting", resolved: "Resolved", closed: "Closed", cancelled: "Cancelled" },
      priority: { low: "Low", normal: "Normal", high: "High", urgent: "Urgent" },
      statusLabel: "Status",
      priorityLabel: "Priority",
      requester: "Requester",
      team: "Team",
      assignedTo: "Assigned to",
      unassigned: "Unassigned",
      created: "Created",
      categoryField: "Category",
      ticketControls: "Manage ticket",
      conversation: "Internal conversation",
      commentsCount: "comments",
      agent: "Agent",
      comment: "Comment",
      commentPlaceholder: "Write an internal comment…",
      noComments: "No comments yet.",
      attachments: "Attachments",
      upload: "Add attachment",
      noAttachments: "No attachments.",
      links: "Links",
      githubIntegration: "GitHub link",
      githubConnectionId: "Connection ID",
      githubOwner: "Owner",
      githubRepository: "Repository",
      githubLink: "Link issue",
      githubUnlink: "Unlink",
      githubLinkError: "The GitHub link could not be saved.",
      githubSettings: "GitHub project integration",
      githubProjectId: "HydraHive project ID",
      githubProjectsLoading: "Loading projects …",
      githubProjectsError: "HydraHive projects could not be loaded.",
      githubProjectsEmpty: "No accessible projects found.",
      githubChooseCredential: "Choose GitHub credential",
      githubChooseOwner: "Choose GitHub owner",
      githubChooseRepository: "Choose GitHub repository",
      githubReposLoading: "Loading project repositories …",
      githubReposError: "Project repositories could not be loaded.",
      githubReposEmpty: "No GitHub repositories with a project token found.",
      githubDiscoveryLoading: "Loading GitHub data …",
      githubDiscoveryError: "GitHub data could not be loaded.",
      githubNoCredential: "No matching GitHub bearer credential. Create one under Credentials.",
      githubChooseConnection: "Choose GitHub connection",
      githubNoConnection: "No GitHub connection for this project",
      githubCredential: "Credential name",
      githubAdd: "Add connection",
      githubDisable: "Disable connection",
      githubSaved: "Connection saved. Open GitHub Workbench above to view issues.",
      githubAlreadyConnected: "This repository is already connected. Open GitHub Workbench above to view issues.",
      githubConnected: "already connected",
      githubAlreadyConnectedShort: "Already connected",
      githubModeSaved: "GitHub write mode saved.",
      githubModeReadOnly: "Read only",
      githubModePush: "Push",
      githubModeBidirectional: "Bidirectional",
      githubSettingsError: "The GitHub connection could not be saved.",
      githubWorkbench: "GitHub workbench",
      githubWorkbenchChooseProject: "Choose a HydraHive project to open GitHub tickets.",
      githubWorkbenchNoConnection: "No GitHub connection is configured for this project.",
      githubWorkbenchError: "The GitHub workbench could not load its data.",
      githubRemoteIssues: "GitHub issues",
      githubRemoteIssuesHint: "Open issues from the connected repository.",
      githubLocalTickets: "HydraHive tickets",
      githubLocalTicketsHint: "Imported issues using the normal HydraHive ticket workflow.",
      githubNoRemoteIssues: "No open GitHub issues found.",
      githubNoImportedTickets: "No issues have been imported as HydraHive tickets yet.",
      githubImportedTicket: "Imported as HydraHive ticket #{number}",
      githubNotImported: "Not imported as a HydraHive ticket yet",
      githubOpenTicket: "Open ticket",
      githubImportTicket: "Import as ticket",
      githubOpenExternal: "Open on GitHub",
      githubSync: "Sync now",
      githubStateOpen: "Open",
      githubStateClosed: "Closed",
      githubStateAll: "All",
      githubIssuesTab: "Issues",
      githubBoardTab: "Project board",
      githubBoardTitle: "GitHub project board",
      githubBoardHint: "Project items and status fields of the selected GitHub Project.",
      githubBoardWriteEnabled: "Write access enabled",
      githubBoardReadOnly: "Read only",
      githubBoardEmpty: "No project items found.",
      githubBoardNoStatus: "No status",
      githubAddToProject: "Add to Project",
      githubSyncDone: "{count} issues synchronized, {created} new tickets created.",
      githubPush: "Push to GitHub",
      githubPushError: "The change could not be synchronized to GitHub.",
      githubLoading: "Loading GitHub data …",
      githubItemsTitle: "GitHub project tasks",
      githubIssuesLoading: "Loading open GitHub issues assigned to you …",
      githubIssuesError: "Assigned GitHub issues could not be loaded.",
      githubIssuesEmpty: "No open issues assigned to your GitHub account were found.",
      githubIssueOpen: "open",
      githubChooseProject: "Choose GitHub Project",
      githubItemsLoading: "Loading GitHub Projects and tasks …",
      githubItemsError: "GitHub Projects or tasks could not be loaded.",
      githubItemsNoConnection: "No GitHub connection is configured for this project.",
      githubItemsNoProjects: "No GitHub Projects found or permission is missing.",
      githubItemsEmpty: "This GitHub Project has no visible tasks.",
      githubItemsUntitled: "Untitled task",
      githubOpenItem: "Open task on GitHub",
      project: "Project",
      task: "Task",
      session: "Session",
      noDescription: "No description.",
      titleField: "Title",
      titlePlaceholder: "Short summary of the issue",
      descriptionField: "Description",
      descriptionPlaceholder: "Describe the problem, context or support you need…",
      categoryPlaceholder: "e.g. Infrastructure",
      cancel: "Cancel",
      create: "Create ticket",
      saving: "Saving…",
      internalOnly: "Visible to authenticated HydraHive users only.",
      saveError: "The change could not be saved.",
      uploadError: "The attachment could not be uploaded.",
      loadError: "Tickets could not be loaded.",
      teams: "Teams",
      teamName: "Team name",
      teamDescription: "Short description (optional)",
      createTeam: "Create team",
      teamError: "Team could not be created (admin permission required).",
      removeMember: "Remove member",
      userId: "User ID",
      addMember: "Add member",
      noTeams: "No teams yet.",
      notifications: "Notifications",
      unread: "unread",
      open: "Open",
      noNotifications: "No new notifications.",
      dueDate: "Due date (manual)",
      manualDueDate: "Manual due date",
      slaDueDate: "SLA due date",
      resetDueDate: "Restore SLA calculation",
      selected: "selected",
      bulkPriority: "Change priority",
      savedViews: "Saved views",
      chooseView: "Choose view",
      viewName: "View name",
      saveView: "Save view",
      deleteView: "Delete view",
      slaProfiles: "SLA profile",
      slaProfilesHint: "Deadlines in hours. Changes apply to new or recalculated tickets.",
      resolution: "Resolution",
      save: "Save",
      dashboard: { open: "Open", overdue: "Overdue", dueSoon: "Due soon", mine: "My tickets", unassigned: "Unassigned" },
      notification: {},
    },
  },
}
