import { AtelierPage } from "./AtelierPage"

export const routes = [{ path: "/atelier", element: <AtelierPage /> }]
export const nav = [
  { path: "/atelier", icon: "Palette", labelKey: "atelier", group: "working", roles: [] },
]

export const i18n = {
  de: {
    atelier: {
      atelier: "Atelier",
      title: "Atelier",
      project: "Projekt",
      no_projects: "Keine Projekte vorhanden. Lege zuerst ein Projekt an.",
      characters: "Charaktere",
      new_character: "Neue Figur",
      edit_character: "Figur bearbeiten",
      no_characters: "Noch keine Figuren.",
      untitled: "Unbenannt",
      char_name: "Name",
      char_description: "Steckbrief (Aussehen, Merkmale — wird wörtlich in jeden Prompt übernommen)",
      char_style: "Stil-Anker (z.B. flat vector, thick outlines)",
      char_palette: "Palette (#hex, kommagetrennt)",
      char_seed: "Seed",
      edit: "Bearbeiten",
      delete: "Löschen",
      delete_confirm: "Diese Figur wirklich löschen?",
      save: "Speichern",
      create: "Anlegen",
      generate: "Szene generieren",
      using_characters: "Mit Figuren",
      no_character_selected: "Keine Figur gewählt — es wird nur nach CI + Szene generiert.",
      scene_placeholder: "Beschreibe nur die Szene, z.B. 'winkt am Strand, sonniger Tag'",
      model: "Modell",
      aspect_ratio: "Format",
      default: "Standard",
      seed_optional: "Seed (optional, nur bei flux.2 / seedream)",
      seed_hint: "leer = zufällig",
      generating: "Generiere…",
      generate_button: "Bild generieren",
      gallery: "Galerie",
      gallery_empty: "Noch keine Bilder. Generiere das erste!",
      promote: "Als Referenz",
      promote_to: "Als Hero-Referenz übernehmen für:",
      close: "Schließen",
      cancel: "Abbrechen",
    },
  },
  en: {
    atelier: {
      atelier: "Atelier",
      title: "Atelier",
      project: "Project",
      no_projects: "No projects yet. Create a project first.",
      characters: "Characters",
      new_character: "New character",
      edit_character: "Edit character",
      no_characters: "No characters yet.",
      untitled: "Untitled",
      char_name: "Name",
      char_description: "Profile (looks, traits — copied verbatim into every prompt)",
      char_style: "Style anchor (e.g. flat vector, thick outlines)",
      char_palette: "Palette (#hex, comma-separated)",
      char_seed: "Seed",
      edit: "Edit",
      delete: "Delete",
      delete_confirm: "Really delete this character?",
      save: "Save",
      create: "Create",
      generate: "Generate scene",
      using_characters: "Using characters",
      no_character_selected: "No character selected — generating from CI + scene only.",
      scene_placeholder: "Describe only the scene, e.g. 'waving at the beach, sunny day'",
      model: "Model",
      aspect_ratio: "Aspect",
      default: "Default",
      seed_optional: "Seed (optional, flux.2 / seedream only)",
      seed_hint: "empty = random",
      generating: "Generating…",
      generate_button: "Generate image",
      gallery: "Gallery",
      gallery_empty: "No images yet. Generate the first one!",
      promote: "As reference",
      promote_to: "Promote as hero reference for:",
      close: "Close",
      cancel: "Cancel",
    },
  },
}
