import { AtelierPage } from "./AtelierPage"

export const routes = [{ path: "/atelier", element: <AtelierPage /> }]
export const nav = [
  { path: "/atelier", icon: "Palette", labelKey: "atelier", group: "working", roles: [] },
]

// Theme-Template-Baustein: <hh-atelier/> in einem Template. Wird vom Core über
// gen-modules (moduleSlotBlocks) optional eingesammelt — nur vorhanden wenn das
// Modul installiert ist, daher kein harter Core→Modul-Import mehr.
export const slotBlocks = [
  {
    name: "atelier",
    label: "Atelier (Bildgenerator)",
    render: (_attrs: Record<string, string>) => (
      <div className="min-h-[200px]"><AtelierPage /></div>
    ),
  },
]

export const i18n = {
  de: {
    atelier: {
      atelier: "Atelier",
      title: "Atelier",
      project: "Projekt",
      tab_characters: "Charaktere",
      tab_generate: "Generieren",
      tab_gallery: "Galerie",
      tab_clips: "Videos",
      tab_audio: "Audio",
      tab_films: "Filme",
      tab_cut: "Schnitt",
      tab_help_characters: "Lege Figuren mit Steckbrief, Referenzbildern und Stil-Anker an. Gewählte Charaktere fließen automatisch in Bild-, Video- und Regie-Workflows ein.",
      tab_help_generate: "Beschreibe eine Szene, wähle Figuren im Charaktere-Tab und erzeuge ein konsistentes Bild. Das Ergebnis landet in der Galerie.",
      tab_help_gallery: "Alle erzeugten Bilder dieses Projekts. Klick öffnet die große Vorschau; als Referenz übernimmt ein Bild in einen Charakter, 🎬 startet ein Video daraus.",
      tab_help_clips: "KI-generierte Clips dieses Projekts. Starte neue Videos aus Bildern oder Text, wiederhole Einstellungen oder nutze den letzten Frame für Fortsetzungen.",
      tab_help_audio: "Erzeuge Musik und verwalte Sound-Profile. Lyria eignet sich für Scores, spätere TTS-Stimmen für Dialoge und Voiceover.",
      tab_help_films: "Setze fertige Clips und Musik zu einem Film zusammen. Clips in gewünschter Reihenfolge auswählen, Musik optional darunterlegen und rendern.",
      tab_help_cut: "Schneide Projekt-Clips direkt im Atelier: Videos aus dem Projekt importieren, In/Out setzen, splitten, Audio hinzufügen und exportieren.",
      tab_help_regie: "Schreibe ein Drehbuch mit Szenen, Charakteren, Dialogen und Musik. Der Regieagent zerlegt es in Shots und rendert nach Freigabe den Film.",
      cut_library_hint: "Importierte Projektvideos für den Schnitt. Atelier-Clips erscheinen über \"Aus Projekt hinzufügen\".",
      cut_add_from_project: "Aus Projekt hinzufügen",
      cut_upload: "Video hochladen",
      cut_empty: "Noch keine Schnitt-Projekte. Füge einen Atelier-Clip aus dem Projekt hinzu oder lade ein Video hoch.",
      cut_clips: "Clips",
      cut_upload_failed: "Upload/Import fehlgeschlagen",
      saving: "Speichert…",
      delete_image_confirm: "Dieses Bild wirklich löschen?",
      delete_video_confirm: "Dieses Video wirklich löschen?",
      delete_film_confirm: "Diesen Film wirklich löschen?",
      no_projects: "Keine Projekte vorhanden. Lege zuerst ein Projekt an.",
      characters: "Charaktere",
      new_character: "Neue Figur",
      edit_character: "Figur bearbeiten",
      no_characters: "Noch keine Figuren.",
      untitled: "Unbenannt",
      char_name: "Name",
      char_description: "Steckbrief (Aussehen, Merkmale — wird wörtlich in jeden Prompt übernommen)",
      char_style: "Stil-Anker (z.B. flat vector, thick outlines)",
      char_palette: "Palette (#hex, kommagetrennt)",
      char_seed: "Seed",
      edit: "Bearbeiten",
      delete: "Löschen",
      delete_confirm: "Diese Figur wirklich löschen?",
      save: "Speichern",
      create: "Anlegen",
      references: "Referenzbilder",
      upload_reference: "Bild hochladen",
      delete_reference: "Referenzbild löschen",
      delete_reference_confirm: "Dieses Referenzbild wirklich löschen?",
      uploading: "Lädt hoch…",
      reference_hint: "Eigene Bilder als Vorlage (max. 3 werden genutzt) — PNG/JPG/WebP, bis 15 MB. Stärkster Konsistenz-Hebel.",
      reference_unused: "Über Limit — wird bei der Generierung nicht genutzt",
      references_after_create: "Nach dem Anlegen kannst du hier Referenzbilder hochladen.",
      generate: "Szene generieren",
      using_characters: "Mit Figuren",
      no_character_selected: "Keine Figur gewählt — es wird nur nach CI + Szene generiert.",
      scene_placeholder: "Beschreibe nur die Szene, z.B. 'winkt am Strand, sonniger Tag'",
      model: "Modell",
      aspect_ratio: "Format",
      default: "Standard",
      seed_optional: "Seed (optional, nur bei flux.2 / seedream)",
      seed_hint: "leer = zufällig",
      generating: "Generiere…",
      generate_button: "Bild generieren",
      style: "Stil-Look",
      style_none: "— Standard (kein fester Stil) —",
      style_photo: "Fotorealistisch",
      style_cinematic: "Filmisch / Cinematic",
      style_flat_vector: "Flat Vector",
      style_watercolor: "Aquarell",
      style_oil_painting: "Ölgemälde",
      style_retro_anime: "Retro-Anime (90er)",
      style_modern_anime: "Modernes Anime",
      style_comic: "Comic",
      style_pixel_art: "Pixel-Art",
      style_3d_render: "3D-Render",
      style_claymation: "Knet-Look (Claymation)",
      style_pencil_sketch: "Bleistift-Skizze",
      style_vintage_tarot: "Vintage-Tarot",
      style_low_poly: "Low-Poly",
      style_papercut: "Papierschnitt",
      style_synthwave: "Synthwave",
      camera_panel: "Regie & Kamera",
      cam_any: "— egal —",
      cam_reset: "Zurücksetzen",
      cam_group_shot: "Kameraeinstellung",
      cam_group_lens: "Objektiv / Brennweite",
      cam_group_light: "Licht",
      cam_group_weather: "Wetter",
      cam_group_time: "Tageszeit",
      cam_group_mood: "Stimmung / Look",
      cam_shot_extreme_closeup: "Extreme Nahaufnahme",
      cam_shot_closeup: "Nahaufnahme",
      cam_shot_medium: "Halbtotale",
      cam_shot_full: "Ganzkörper",
      cam_shot_wide: "Totale",
      cam_shot_aerial: "Vogelperspektive",
      cam_shot_low_angle: "Froschperspektive",
      cam_shot_high_angle: "Aufsicht",
      cam_shot_over_shoulder: "Over-the-Shoulder",
      cam_shot_dutch: "Schräge (Dutch Angle)",
      cam_lens_wide_24: "24mm Weitwinkel",
      cam_lens_normal_50: "50mm natürlich",
      cam_lens_portrait_85: "85mm Porträt (Bokeh)",
      cam_lens_tele_135: "135mm Tele",
      cam_lens_macro: "Makro",
      cam_lens_fisheye: "Fischauge",
      cam_lens_anamorphic: "Anamorph (Kino)",
      cam_light_golden_hour: "Goldene Stunde",
      cam_light_soft: "Weiches Licht",
      cam_light_rembrandt: "Rembrandt",
      cam_light_backlit: "Gegenlicht",
      cam_light_studio: "Studio",
      cam_light_neon: "Neon",
      cam_light_hard: "Hartes Licht",
      cam_light_candle: "Kerzenlicht",
      cam_light_overcast: "Bewölkt (flach)",
      cam_weather_clear: "Klar",
      cam_weather_rain: "Regen",
      cam_weather_storm: "Sturm",
      cam_weather_snow: "Schnee",
      cam_weather_fog: "Nebel",
      cam_weather_cloudy: "Bewölkt",
      cam_weather_wet_street: "Nasse Straße",
      cam_weather_windy: "Windig",
      cam_time_dawn: "Morgengrauen",
      cam_time_morning: "Morgen",
      cam_time_noon: "Mittag",
      cam_time_afternoon: "Nachmittag",
      cam_time_dusk: "Abenddämmerung",
      cam_time_night: "Nacht",
      cam_time_blue_hour: "Blaue Stunde",
      cam_mood_teal_orange: "Kino (Teal-Orange)",
      cam_mood_warm: "Warm",
      cam_mood_cool: "Kühl",
      cam_mood_desaturated: "Entsättigt",
      cam_mood_pastel: "Pastell",
      cam_mood_moody: "Düster",
      cam_mood_vibrant: "Kräftig",
      cam_mood_noir: "Film Noir (S/W)",
      gallery: "Galerie",
      gallery_empty: "Noch keine Bilder. Generiere das erste!",
      gallery_items: "Bilder",
      gallery_view_small: "Klein",
      gallery_view_medium: "Mittel",
      gallery_view_large: "Groß",
      gallery_view_list: "Liste",
      open: "Öffnen",
      details: "Details",
      file: "Datei",
      promote: "Als Referenz",
      promote_to: "Als Hero-Referenz übernehmen für:",
      close: "Schließen",
      cancel: "Abbrechen",
      videos: "Videos",
      video_items: "Clips",
      video_empty: "Noch keine Videos. Erzeuge ein Video aus einem Galerie-Bild oder starte ein Text-Video.",
      make_video: "Zu Video machen",
      make_video_text: "Video aus Text",
      video_motion: "Bewegung / Beschreibung",
      video_aspect: "Format",
      video_aspect_hint: "Hinweis: Bei einem Startbild richtet sich das Video oft nach dessen Format. Für ein anderes Format erzeuge das Startbild im gewünschten Format.",
      video_motion_hint: "z.B. 'Kamera fährt langsam ran, Figur winkt'",
      video_duration: "Dauer",
      video_end_image: "Endbild (optional)",
      video_end_image_none: "— kein Endbild —",
      video_end_image_loop: "Startbild als Endbild",
      video_end_image_hint: "Das Video bewegt sich vom Startbild zu diesem Endbild. Für einen Loop kann dasselbe Startbild gewählt werden. Nur bei Modellen mit last_frame-Unterstützung.",
      video_cost_hint: "⚠ Video ist deutlich teurer als ein Bild und dauert 1-2 Minuten.",
      video_start: "Video erstellen",
      video_starting: "Startet…",
      video_generating: "Video wird erstellt… (1-2 Min)",
      video_failed: "Video fehlgeschlagen",
      continue_video: "Fortsetzen",
      continue_extracting: "Hole letzten Frame…",
      continue_hint: "Letzten Frame als Startbild nehmen → nahtloser Anschluss-Clip",
      repeat_video: "Wiederholen",
      repeat_hint: "Öffnet den Dialog mit genau diesem Prompt/Modell/Dauer — vor dem Generieren noch anpassbar",
      repeat_uses_reference: "Startbild/Referenz des Originals wird wiederverwendet",
      repeat_image: "Wiederholen",
      video_meta_model: "Verwendetes Modell",
      video_meta_duration: "Dauer",
      video_meta_aspect: "Format",
      video_meta_source: "Wie erzeugt",
      video_meta_i2v: "aus Startbild",
      video_meta_t2v: "aus Text",
      prompt_expand: "mehr",
      prompt_collapse: "weniger",
      prompt_copy: "Prompt kopieren",
      prompt_copied: "kopiert",
      film_title: "Film schneiden",
      film_empty: "Noch keine Clips. Erzeuge erst Videos (Tab „Videos“), dann fügst du sie hier zusammen.",
      film_hint: "Clips in gewünschter Reihenfolge anklicken, dann rendern (gemischte Formate werden eingepasst).",
      film_render: "Film rendern ({{n}})",
      film_rendering: "Rendert…",
      film_processing: "Film wird zusammengesetzt…",
      film_failed: "Rendern fehlgeschlagen",
      film_music: "Musik unterlegen",
      film_music_none: "— keine Musik —",
      audio_profiles: "Sound-Profile",
      audio_new_profile: "Neues Profil",
      audio_edit_profile: "Profil bearbeiten",
      audio_no_profiles: "Noch keine Sound-Profile.",
      audio_profile_name: "Name (z.B. Hauptthema)",
      audio_profile_description: "Beschreibung (Genre, Stimmung, Instrumente, BPM — wird wörtlich in jeden Prompt übernommen)",
      audio_delete_profile_confirm: "Dieses Sound-Profil wirklich löschen?",
      audio_studio_sound: "Studio-Sound (CI)",
      audio_studio_sound_placeholder: "Übergreifender Klang der Serie, z.B. 'orchestral, episch, warme Streicher'",
      audio_scene: "Szene",
      audio_scene_placeholder: "Beschreibe nur das Variable, z.B. 'treibender Loop für die Verfolgungsjagd'",
      audio_generate: "Musik generieren",
      audio_generating: "Generiere… (10-30s)",
      audio_library: "Bibliothek",
      audio_library_empty: "Noch keine Tracks. Generiere den ersten!",
      audio_delete_track_confirm: "Diesen Track wirklich löschen?",
      tab_regie: "Regie",
      regie_head: "Drehbuch",
      regie_title_placeholder: "Filmtitel …",
      regie_logline_placeholder: "Logline — der Film in einem Satz",
      regie_description_placeholder: "Wie soll der Film allgemein werden? (Genre, Ton, Look, Story-Idee)",
      regie_film_model: "Film-Modell",
      regie_audio_model: "Audio-Modell",
      regie_aspect: "Format",
      regie_default_duration: "Standard-Dauer (Sek.)",
      model_auto_default: "— Standard —",
      scene_word: "Szene",
      scenes_word: "Szenen",
      scene_add: "Szene hinzufügen",
      scenes_empty: "Noch keine Szenen. Füge die erste hinzu!",
      scene_delete_confirm: "Diese Szene wirklich löschen?",
      scene_title_placeholder: "Szenen-Titel",
      scene_description_placeholder: "Was passiert in dieser Szene?",
      scene_location: "Ort",
      scene_time: "Tageszeit",
      scene_characters: "Charaktere in dieser Szene",
      scene_dialogues: "Dialoge",
      scene_dialogue_add: "Dialog",
      scene_dialogue_line: "Was wird gesagt?",
      scene_dialogue_emotion: "Emotion",
      scene_music: "Musik-Untermalung",
      scene_music_placeholder: "z.B. melancholisches Cello, langsam",
      scene_music_hint: "Wird beim Rendern erzeugt und ab dieser Szene leise unter den Original-Ton gelegt.",
      scene_save: "Szene speichern",
      shots_word: "Shots",
      decompose_send: "An Regieagent senden",
      decompose_running: "Regieagent zerlegt…",
      decompose_hint: "Der Regieagent zerlegt jede Szene in konkrete Shots (Kamera + Prompt + Charaktere). Es wird noch nichts generiert.",
      decompose_done: "Fertig: {{scenes}} Szenen → {{shots}} Shots. Prüfen & anpassen, dann später rendern.",
      decompose_failed: "Regieagent fehlgeschlagen. Ist ein LLM-Modell konfiguriert?",
      render_send: "Freigeben & generieren",
      render_hint: "Erzeugt je Shot ein Keyframe-Bild und daraus einen Video-Clip, dann einen Film. Kostet echte Generierungen und dauert.",
      render_confirm: "Jetzt alle Shots rendern? Das erzeugt Bilder + Videos (kostenpflichtig) und kann dauern.",
      render_running: "Rendert…",
      render_done: "Fertig: {{n}} Clips gerendert. Film wird zusammengesetzt.",
      render_done_errors: "Fertig: {{done}} ok, {{failed}} fehlgeschlagen. Film aus den fertigen Clips.",
      render_failed: "Render fehlgeschlagen.",
      shot_status_image_ready: "Bild ✓",
      shot_status_video_processing: "Video…",
      shot_status_done: "fertig",
      shot_status_failed: "Fehler",
    },
  },
  en: {
    atelier: {
      atelier: "Atelier",
      title: "Atelier",
      project: "Project",
      tab_characters: "Characters",
      tab_generate: "Generate",
      tab_gallery: "Gallery",
      tab_clips: "Videos",
      tab_audio: "Audio",
      tab_films: "Films",
      tab_cut: "Edit",
      tab_help_characters: "Create characters with profiles, reference images and style anchors. Selected characters are reused by image, video and direction workflows.",
      tab_help_generate: "Describe a scene, select characters in the Characters tab and generate a consistent image. The result appears in the Gallery.",
      tab_help_gallery: "All generated images for this project. Click for the large preview; promote stores an image as a character reference, 🎬 starts a video from it.",
      tab_help_clips: "Generated clips for this project. Start videos from images or text, repeat settings, or grab the last frame for continuation clips.",
      tab_help_audio: "Generate music and manage sound profiles. Lyria is useful for scores; later TTS voices can produce dialogue and voiceover.",
      tab_help_films: "Assemble finished clips and music into a film. Select clips in order, optionally add music, then render.",
      tab_help_cut: "Cut project clips directly inside Atelier: import project videos, set in/out, split, add audio and export.",
      tab_help_regie: "Write a screenplay with scenes, characters, dialogue and music. The director agent turns it into shots and renders the film after approval.",
      cut_library_hint: "Imported project videos for editing. Atelier clips appear via \"Add from project\".",
      cut_add_from_project: "Add from project",
      cut_upload: "Upload video",
      cut_empty: "No edit projects yet. Add an Atelier clip from the project or upload a video.",
      cut_clips: "clips",
      cut_upload_failed: "Upload/import failed",
      saving: "Saving…",
      delete_image_confirm: "Really delete this image?",
      delete_video_confirm: "Really delete this video?",
      delete_film_confirm: "Really delete this film?",
      no_projects: "No projects yet. Create a project first.",
      characters: "Characters",
      new_character: "New character",
      edit_character: "Edit character",
      no_characters: "No characters yet.",
      untitled: "Untitled",
      char_name: "Name",
      char_description: "Profile (looks, traits — copied verbatim into every prompt)",
      char_style: "Style anchor (e.g. flat vector, thick outlines)",
      char_palette: "Palette (#hex, comma-separated)",
      char_seed: "Seed",
      edit: "Edit",
      delete: "Delete",
      delete_confirm: "Really delete this character?",
      save: "Save",
      create: "Create",
      references: "Reference images",
      upload_reference: "Upload image",
      delete_reference: "Delete reference image",
      delete_reference_confirm: "Really delete this reference image?",
      uploading: "Uploading…",
      reference_hint: "Your own images as a template (max 3 used) — PNG/JPG/WebP, up to 15 MB. Strongest consistency lever.",
      reference_unused: "Over the limit — not used during generation",
      references_after_create: "After creating, you can upload reference images here.",
      generate: "Generate scene",
      using_characters: "Using characters",
      no_character_selected: "No character selected — generating from CI + scene only.",
      scene_placeholder: "Describe only the scene, e.g. 'waving at the beach, sunny day'",
      model: "Model",
      aspect_ratio: "Aspect",
      default: "Default",
      seed_optional: "Seed (optional, flux.2 / seedream only)",
      seed_hint: "empty = random",
      generating: "Generating…",
      generate_button: "Generate image",
      style: "Style look",
      style_none: "— Default (no fixed style) —",
      style_photo: "Photorealistic",
      style_cinematic: "Cinematic",
      style_flat_vector: "Flat vector",
      style_watercolor: "Watercolor",
      style_oil_painting: "Oil painting",
      style_retro_anime: "Retro anime (90s)",
      style_modern_anime: "Modern anime",
      style_comic: "Comic",
      style_pixel_art: "Pixel art",
      style_3d_render: "3D render",
      style_claymation: "Claymation",
      style_pencil_sketch: "Pencil sketch",
      style_vintage_tarot: "Vintage tarot",
      style_low_poly: "Low poly",
      style_papercut: "Papercut",
      style_synthwave: "Synthwave",
      camera_panel: "Direction & Camera",
      cam_any: "— any —",
      cam_reset: "Reset",
      cam_group_shot: "Shot type",
      cam_group_lens: "Lens / Focal length",
      cam_group_light: "Lighting",
      cam_group_weather: "Weather",
      cam_group_time: "Time of day",
      cam_group_mood: "Mood / Look",
      cam_shot_extreme_closeup: "Extreme close-up",
      cam_shot_closeup: "Close-up",
      cam_shot_medium: "Medium shot",
      cam_shot_full: "Full body",
      cam_shot_wide: "Wide / Establishing",
      cam_shot_aerial: "Aerial / Bird's-eye",
      cam_shot_low_angle: "Low angle",
      cam_shot_high_angle: "High angle",
      cam_shot_over_shoulder: "Over-the-shoulder",
      cam_shot_dutch: "Dutch angle",
      cam_lens_wide_24: "24mm wide-angle",
      cam_lens_normal_50: "50mm natural",
      cam_lens_portrait_85: "85mm portrait (bokeh)",
      cam_lens_tele_135: "135mm telephoto",
      cam_lens_macro: "Macro",
      cam_lens_fisheye: "Fisheye",
      cam_lens_anamorphic: "Anamorphic (cinema)",
      cam_light_golden_hour: "Golden hour",
      cam_light_soft: "Soft light",
      cam_light_rembrandt: "Rembrandt",
      cam_light_backlit: "Backlit",
      cam_light_studio: "Studio",
      cam_light_neon: "Neon",
      cam_light_hard: "Hard light",
      cam_light_candle: "Candlelight",
      cam_light_overcast: "Overcast (flat)",
      cam_weather_clear: "Clear",
      cam_weather_rain: "Rain",
      cam_weather_storm: "Storm",
      cam_weather_snow: "Snow",
      cam_weather_fog: "Fog",
      cam_weather_cloudy: "Cloudy",
      cam_weather_wet_street: "Wet street",
      cam_weather_windy: "Windy",
      cam_time_dawn: "Dawn",
      cam_time_morning: "Morning",
      cam_time_noon: "Noon",
      cam_time_afternoon: "Afternoon",
      cam_time_dusk: "Dusk",
      cam_time_night: "Night",
      cam_time_blue_hour: "Blue hour",
      cam_mood_teal_orange: "Cinematic (teal-orange)",
      cam_mood_warm: "Warm",
      cam_mood_cool: "Cool",
      cam_mood_desaturated: "Desaturated",
      cam_mood_pastel: "Pastel",
      cam_mood_moody: "Moody",
      cam_mood_vibrant: "Vibrant",
      cam_mood_noir: "Film noir (B&W)",
      gallery: "Gallery",
      gallery_empty: "No images yet. Generate the first one!",
      gallery_items: "images",
      gallery_view_small: "Small",
      gallery_view_medium: "Medium",
      gallery_view_large: "Large",
      gallery_view_list: "List",
      open: "Open",
      details: "Details",
      file: "File",
      promote: "As reference",
      promote_to: "Promote as hero reference for:",
      close: "Close",
      cancel: "Cancel",
      videos: "Videos",
      video_items: "clips",
      video_empty: "No videos yet. Create one from a gallery image or start a text video.",
      make_video: "Make video",
      make_video_text: "Video from text",
      video_motion: "Motion / Description",
      video_aspect: "Aspect",
      video_aspect_hint: "Note: with a start image the video often follows its aspect. For a different aspect, create the start image in that aspect.",
      video_motion_hint: "e.g. 'camera slowly pushes in, character waves'",
      video_duration: "Duration",
      video_end_image: "End image (optional)",
      video_end_image_none: "— no end image —",
      video_end_image_loop: "Use start image as end",
      video_end_image_hint: "The video morphs from the start image to this end image. For a loop, the same start image can be selected. Only for models that support last_frame.",
      video_cost_hint: "⚠ Video is much pricier than an image and takes 1-2 minutes.",
      video_start: "Create video",
      video_starting: "Starting…",
      video_generating: "Creating video… (1-2 min)",
      video_failed: "Video failed",
      continue_video: "Continue",
      continue_extracting: "Grabbing last frame…",
      continue_hint: "Use the last frame as start image → seamless follow-up clip",
      repeat_video: "Repeat",
      repeat_hint: "Opens the dialog with this exact prompt/model/duration — still editable before generating",
      repeat_uses_reference: "Reusing the original's start image / reference",
      repeat_image: "Repeat",
      video_meta_model: "Model used",
      video_meta_duration: "Duration",
      video_meta_aspect: "Aspect ratio",
      video_meta_source: "How it was made",
      video_meta_i2v: "from start image",
      video_meta_t2v: "from text",
      prompt_expand: "more",
      prompt_collapse: "less",
      prompt_copy: "Copy prompt",
      prompt_copied: "copied",
      film_title: "Edit film",
      film_empty: "No clips yet. Create videos first (\"Videos\" tab), then combine them here.",
      film_hint: "Click clips in the desired order, then render (mixed formats are letterboxed).",
      film_render: "Render film ({{n}})",
      film_rendering: "Rendering…",
      film_processing: "Assembling film…",
      film_failed: "Render failed",
      film_music: "Underlay music",
      film_music_none: "— no music —",
      audio_profiles: "Sound profiles",
      audio_new_profile: "New profile",
      audio_edit_profile: "Edit profile",
      audio_no_profiles: "No sound profiles yet.",
      audio_profile_name: "Name (e.g. Main theme)",
      audio_profile_description: "Description (genre, mood, instruments, BPM — copied verbatim into every prompt)",
      audio_delete_profile_confirm: "Really delete this sound profile?",
      audio_studio_sound: "Studio sound (CI)",
      audio_studio_sound_placeholder: "Overarching sound of the series, e.g. 'orchestral, epic, warm strings'",
      audio_scene: "Scene",
      audio_scene_placeholder: "Describe only the variable part, e.g. 'driving loop for the chase scene'",
      audio_generate: "Generate music",
      audio_generating: "Generating… (10-30s)",
      audio_library: "Library",
      audio_library_empty: "No tracks yet. Generate the first one!",
      audio_delete_track_confirm: "Really delete this track?",
      tab_regie: "Direction",
      regie_head: "Screenplay",
      regie_title_placeholder: "Film title …",
      regie_logline_placeholder: "Logline — the film in one sentence",
      regie_description_placeholder: "What should the film be like overall? (genre, tone, look, story idea)",
      regie_film_model: "Film model",
      regie_audio_model: "Audio model",
      regie_aspect: "Aspect",
      regie_default_duration: "Default duration (sec)",
      model_auto_default: "— Default —",
      scene_word: "Scene",
      scenes_word: "Scenes",
      scene_add: "Add scene",
      scenes_empty: "No scenes yet. Add the first one!",
      scene_delete_confirm: "Really delete this scene?",
      scene_title_placeholder: "Scene title",
      scene_description_placeholder: "What happens in this scene?",
      scene_location: "Location",
      scene_time: "Time of day",
      scene_characters: "Characters in this scene",
      scene_dialogues: "Dialogue",
      scene_dialogue_add: "Line",
      scene_dialogue_line: "What is said?",
      scene_dialogue_emotion: "Emotion",
      scene_music: "Background music",
      scene_music_placeholder: "e.g. melancholic cello, slow",
      scene_music_hint: "Generated at render time and mixed quietly under the original audio from this scene onward.",
      scene_save: "Save scene",
      shots_word: "Shots",
      decompose_send: "Send to director",
      decompose_running: "Director is breaking it down…",
      decompose_hint: "The director agent breaks each scene into concrete shots (camera + prompt + characters). Nothing is generated yet.",
      decompose_done: "Done: {{scenes}} scenes → {{shots}} shots. Review & adjust, then render later.",
      decompose_failed: "Director failed. Is an LLM model configured?",
      render_send: "Approve & generate",
      render_hint: "Generates a keyframe image and a video clip per shot, then a film. Uses real generations and takes a while.",
      render_confirm: "Render all shots now? This creates images + videos (paid) and can take a while.",
      render_running: "Rendering…",
      render_done: "Done: {{n}} clips rendered. Assembling film.",
      render_done_errors: "Done: {{done}} ok, {{failed}} failed. Film from the finished clips.",
      render_failed: "Render failed.",
      shot_status_image_ready: "Image ✓",
      shot_status_video_processing: "Video…",
      shot_status_done: "done",
      shot_status_failed: "Error",
    },
  },
}
