import { AtelierPage } from "./AtelierPage"

export const routes = [{ path: "/atelier", element: <AtelierPage /> }]
export const nav = [
  { path: "/atelier", icon: "Palette", labelKey: "atelier", group: "working", roles: [] },
]

export const i18n = {
  de: {
    atelier: {
      atelier: "Atelier",
      title: "Atelier",
      project: "Projekt",
      tab_generate: "Generieren",
      tab_gallery: "Galerie",
      tab_clips: "Videos",
      delete_image_confirm: "Dieses Bild wirklich löschen?",
      delete_video_confirm: "Dieses Video wirklich löschen?",
      delete_film_confirm: "Diesen Film wirklich löschen?",
      no_projects: "Keine Projekte vorhanden. Lege zuerst ein Projekt an.",
      characters: "Charaktere",
      new_character: "Neue Figur",
      edit_character: "Figur bearbeiten",
      no_characters: "Noch keine Figuren.",
      untitled: "Unbenannt",
      char_name: "Name",
      char_description: "Steckbrief (Aussehen, Merkmale — wird wörtlich in jeden Prompt übernommen)",
      char_style: "Stil-Anker (z.B. flat vector, thick outlines)",
      char_palette: "Palette (#hex, kommagetrennt)",
      char_seed: "Seed",
      edit: "Bearbeiten",
      delete: "Löschen",
      delete_confirm: "Diese Figur wirklich löschen?",
      save: "Speichern",
      create: "Anlegen",
      references: "Referenzbilder",
      upload_reference: "Bild hochladen",
      uploading: "Lädt hoch…",
      reference_hint: "Eigene Bilder als Vorlage (max. 3 werden genutzt) — PNG/JPG/WebP, bis 15 MB. Stärkster Konsistenz-Hebel.",
      reference_unused: "Über Limit — wird bei der Generierung nicht genutzt",
      references_after_create: "Nach dem Anlegen kannst du hier Referenzbilder hochladen.",
      generate: "Szene generieren",
      using_characters: "Mit Figuren",
      no_character_selected: "Keine Figur gewählt — es wird nur nach CI + Szene generiert.",
      scene_placeholder: "Beschreibe nur die Szene, z.B. 'winkt am Strand, sonniger Tag'",
      model: "Modell",
      aspect_ratio: "Format",
      default: "Standard",
      seed_optional: "Seed (optional, nur bei flux.2 / seedream)",
      seed_hint: "leer = zufällig",
      generating: "Generiere…",
      generate_button: "Bild generieren",
      style: "Stil-Look",
      style_none: "— Standard (kein fester Stil) —",
      style_photo: "Fotorealistisch",
      style_cinematic: "Filmisch / Cinematic",
      style_flat_vector: "Flat Vector",
      style_watercolor: "Aquarell",
      style_oil_painting: "Ölgemälde",
      style_retro_anime: "Retro-Anime (90er)",
      style_modern_anime: "Modernes Anime",
      style_comic: "Comic",
      style_pixel_art: "Pixel-Art",
      style_3d_render: "3D-Render",
      style_claymation: "Knet-Look (Claymation)",
      style_pencil_sketch: "Bleistift-Skizze",
      style_vintage_tarot: "Vintage-Tarot",
      style_low_poly: "Low-Poly",
      style_papercut: "Papierschnitt",
      style_synthwave: "Synthwave",
      camera_panel: "Regie & Kamera",
      cam_any: "— egal —",
      cam_reset: "Zurücksetzen",
      cam_group_shot: "Kameraeinstellung",
      cam_group_lens: "Objektiv / Brennweite",
      cam_group_light: "Licht",
      cam_group_weather: "Wetter",
      cam_group_time: "Tageszeit",
      cam_group_mood: "Stimmung / Look",
      cam_shot_extreme_closeup: "Extreme Nahaufnahme",
      cam_shot_closeup: "Nahaufnahme",
      cam_shot_medium: "Halbtotale",
      cam_shot_full: "Ganzkörper",
      cam_shot_wide: "Totale",
      cam_shot_aerial: "Vogelperspektive",
      cam_shot_low_angle: "Froschperspektive",
      cam_shot_high_angle: "Aufsicht",
      cam_shot_over_shoulder: "Over-the-Shoulder",
      cam_shot_dutch: "Schräge (Dutch Angle)",
      cam_lens_wide_24: "24mm Weitwinkel",
      cam_lens_normal_50: "50mm natürlich",
      cam_lens_portrait_85: "85mm Porträt (Bokeh)",
      cam_lens_tele_135: "135mm Tele",
      cam_lens_macro: "Makro",
      cam_lens_fisheye: "Fischauge",
      cam_lens_anamorphic: "Anamorph (Kino)",
      cam_light_golden_hour: "Goldene Stunde",
      cam_light_soft: "Weiches Licht",
      cam_light_rembrandt: "Rembrandt",
      cam_light_backlit: "Gegenlicht",
      cam_light_studio: "Studio",
      cam_light_neon: "Neon",
      cam_light_hard: "Hartes Licht",
      cam_light_candle: "Kerzenlicht",
      cam_light_overcast: "Bewölkt (flach)",
      cam_weather_clear: "Klar",
      cam_weather_rain: "Regen",
      cam_weather_storm: "Sturm",
      cam_weather_snow: "Schnee",
      cam_weather_fog: "Nebel",
      cam_weather_cloudy: "Bewölkt",
      cam_weather_wet_street: "Nasse Straße",
      cam_weather_windy: "Windig",
      cam_time_dawn: "Morgengrauen",
      cam_time_morning: "Morgen",
      cam_time_noon: "Mittag",
      cam_time_afternoon: "Nachmittag",
      cam_time_dusk: "Abenddämmerung",
      cam_time_night: "Nacht",
      cam_time_blue_hour: "Blaue Stunde",
      cam_mood_teal_orange: "Kino (Teal-Orange)",
      cam_mood_warm: "Warm",
      cam_mood_cool: "Kühl",
      cam_mood_desaturated: "Entsättigt",
      cam_mood_pastel: "Pastell",
      cam_mood_moody: "Düster",
      cam_mood_vibrant: "Kräftig",
      cam_mood_noir: "Film Noir (S/W)",
      gallery: "Galerie",
      gallery_empty: "Noch keine Bilder. Generiere das erste!",
      promote: "Als Referenz",
      promote_to: "Als Hero-Referenz übernehmen für:",
      close: "Schließen",
      cancel: "Abbrechen",
      videos: "Videos",
      make_video: "Zu Video machen",
      make_video_text: "Video aus Text",
      video_motion: "Bewegung / Beschreibung",
      video_motion_hint: "z.B. 'Kamera fährt langsam ran, Figur winkt'",
      video_duration: "Dauer",
      video_cost_hint: "⚠ Video ist deutlich teurer als ein Bild und dauert 1-2 Minuten.",
      video_start: "Video erstellen",
      video_starting: "Startet…",
      video_generating: "Video wird erstellt… (1-2 Min)",
      video_failed: "Video fehlgeschlagen",
      continue_video: "Fortsetzen",
      continue_extracting: "Hole letzten Frame…",
      continue_hint: "Letzten Frame als Startbild nehmen → nahtloser Anschluss-Clip",
      film_title: "Film schneiden",
      film_empty: "Noch keine Clips. Erzeuge erst Videos (Tab „Videos“), dann fügst du sie hier zusammen.",
      film_hint: "Clips in gewünschter Reihenfolge anklicken, dann rendern (gemischte Formate werden eingepasst).",
      film_render: "Film rendern ({{n}})",
      film_rendering: "Rendert…",
      film_processing: "Film wird zusammengesetzt…",
      film_failed: "Rendern fehlgeschlagen",
    },
  },
  en: {
    atelier: {
      atelier: "Atelier",
      title: "Atelier",
      project: "Project",
      tab_generate: "Generate",
      tab_gallery: "Gallery",
      tab_clips: "Videos",
      delete_image_confirm: "Really delete this image?",
      delete_video_confirm: "Really delete this video?",
      delete_film_confirm: "Really delete this film?",
      no_projects: "No projects yet. Create a project first.",
      characters: "Characters",
      new_character: "New character",
      edit_character: "Edit character",
      no_characters: "No characters yet.",
      untitled: "Untitled",
      char_name: "Name",
      char_description: "Profile (looks, traits — copied verbatim into every prompt)",
      char_style: "Style anchor (e.g. flat vector, thick outlines)",
      char_palette: "Palette (#hex, comma-separated)",
      char_seed: "Seed",
      edit: "Edit",
      delete: "Delete",
      delete_confirm: "Really delete this character?",
      save: "Save",
      create: "Create",
      references: "Reference images",
      upload_reference: "Upload image",
      uploading: "Uploading…",
      reference_hint: "Your own images as a template (max 3 used) — PNG/JPG/WebP, up to 15 MB. Strongest consistency lever.",
      reference_unused: "Over the limit — not used during generation",
      references_after_create: "After creating, you can upload reference images here.",
      generate: "Generate scene",
      using_characters: "Using characters",
      no_character_selected: "No character selected — generating from CI + scene only.",
      scene_placeholder: "Describe only the scene, e.g. 'waving at the beach, sunny day'",
      model: "Model",
      aspect_ratio: "Aspect",
      default: "Default",
      seed_optional: "Seed (optional, flux.2 / seedream only)",
      seed_hint: "empty = random",
      generating: "Generating…",
      generate_button: "Generate image",
      style: "Style look",
      style_none: "— Default (no fixed style) —",
      style_photo: "Photorealistic",
      style_cinematic: "Cinematic",
      style_flat_vector: "Flat vector",
      style_watercolor: "Watercolor",
      style_oil_painting: "Oil painting",
      style_retro_anime: "Retro anime (90s)",
      style_modern_anime: "Modern anime",
      style_comic: "Comic",
      style_pixel_art: "Pixel art",
      style_3d_render: "3D render",
      style_claymation: "Claymation",
      style_pencil_sketch: "Pencil sketch",
      style_vintage_tarot: "Vintage tarot",
      style_low_poly: "Low poly",
      style_papercut: "Papercut",
      style_synthwave: "Synthwave",
      camera_panel: "Direction & Camera",
      cam_any: "— any —",
      cam_reset: "Reset",
      cam_group_shot: "Shot type",
      cam_group_lens: "Lens / Focal length",
      cam_group_light: "Lighting",
      cam_group_weather: "Weather",
      cam_group_time: "Time of day",
      cam_group_mood: "Mood / Look",
      cam_shot_extreme_closeup: "Extreme close-up",
      cam_shot_closeup: "Close-up",
      cam_shot_medium: "Medium shot",
      cam_shot_full: "Full body",
      cam_shot_wide: "Wide / Establishing",
      cam_shot_aerial: "Aerial / Bird's-eye",
      cam_shot_low_angle: "Low angle",
      cam_shot_high_angle: "High angle",
      cam_shot_over_shoulder: "Over-the-shoulder",
      cam_shot_dutch: "Dutch angle",
      cam_lens_wide_24: "24mm wide-angle",
      cam_lens_normal_50: "50mm natural",
      cam_lens_portrait_85: "85mm portrait (bokeh)",
      cam_lens_tele_135: "135mm telephoto",
      cam_lens_macro: "Macro",
      cam_lens_fisheye: "Fisheye",
      cam_lens_anamorphic: "Anamorphic (cinema)",
      cam_light_golden_hour: "Golden hour",
      cam_light_soft: "Soft light",
      cam_light_rembrandt: "Rembrandt",
      cam_light_backlit: "Backlit",
      cam_light_studio: "Studio",
      cam_light_neon: "Neon",
      cam_light_hard: "Hard light",
      cam_light_candle: "Candlelight",
      cam_light_overcast: "Overcast (flat)",
      cam_weather_clear: "Clear",
      cam_weather_rain: "Rain",
      cam_weather_storm: "Storm",
      cam_weather_snow: "Snow",
      cam_weather_fog: "Fog",
      cam_weather_cloudy: "Cloudy",
      cam_weather_wet_street: "Wet street",
      cam_weather_windy: "Windy",
      cam_time_dawn: "Dawn",
      cam_time_morning: "Morning",
      cam_time_noon: "Noon",
      cam_time_afternoon: "Afternoon",
      cam_time_dusk: "Dusk",
      cam_time_night: "Night",
      cam_time_blue_hour: "Blue hour",
      cam_mood_teal_orange: "Cinematic (teal-orange)",
      cam_mood_warm: "Warm",
      cam_mood_cool: "Cool",
      cam_mood_desaturated: "Desaturated",
      cam_mood_pastel: "Pastel",
      cam_mood_moody: "Moody",
      cam_mood_vibrant: "Vibrant",
      cam_mood_noir: "Film noir (B&W)",
      gallery: "Gallery",
      gallery_empty: "No images yet. Generate the first one!",
      promote: "As reference",
      promote_to: "Promote as hero reference for:",
      close: "Close",
      cancel: "Cancel",
      videos: "Videos",
      make_video: "Make video",
      make_video_text: "Video from text",
      video_motion: "Motion / Description",
      video_motion_hint: "e.g. 'camera slowly pushes in, character waves'",
      video_duration: "Duration",
      video_cost_hint: "⚠ Video is much pricier than an image and takes 1-2 minutes.",
      video_start: "Create video",
      video_starting: "Starting…",
      video_generating: "Creating video… (1-2 min)",
      video_failed: "Video failed",
      continue_video: "Continue",
      continue_extracting: "Grabbing last frame…",
      continue_hint: "Use the last frame as start image → seamless follow-up clip",
      film_title: "Edit film",
      film_empty: "No clips yet. Create videos first (\"Videos\" tab), then combine them here.",
      film_hint: "Click clips in the desired order, then render (mixed formats are letterboxed).",
      film_render: "Render film ({{n}})",
      film_rendering: "Rendering…",
      film_processing: "Assembling film…",
      film_failed: "Render failed",
    },
  },
}
